
INSERT INTO ships (ship_name, home_port)
VALUES ('Albion', 'Fairhaven')
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id);


SET @ship_albion_id := (SELECT id FROM ships WHERE ship_name = 'Albion');


INSERT INTO voyages (
    ship_id, starting_port, destination_port, captain_name, crew_count, casualties, start_date
) VALUES (
             @ship_albion_id, 'Fairhaven', 'Pacific Ocean (Whaling)', 'J. F. Hinds', 0, 0, '1854-11-08 00:00:00'
         );


SET @voyage_albion_id := (SELECT id FROM voyages WHERE ship_id = @ship_albion_id);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1854-11-08 00:00:00', 'Fairhaven, MA (Departure)', 41.637, -70.903, 'took pilot; discharged pilot; secured anchor', 'fresh breezes; fresh gales', 'W.N.W.', 'Southward', JSON_ARRAY(JSON_OBJECT('name','John Howland','home_port','New Bedford'), JSON_OBJECT('name','Waverly','home_port','New Bedford')), JSON_OBJECT(), 'double reefed topsails; Sailed in company with John Howland & Waverly.', 0, 0),
    (@voyage_albion_id, '1854-11-15 00:00:00', 'Atlantic Ocean (Outward)', 38.867, -58.333, 'routine sailing; rigging work', 'brisk wind', 'S[OUTHWAR]d & E[ASTWAR]d', 'E to EN.E.', JSON_ARRAY(JSON_OBJECT('name','bark','home_port',NULL)), JSON_OBJECT(), 'passed a bark on the opposite tack.', 0, 0),
    (@voyage_albion_id, '1854-11-19 00:00:00', 'Atlantic Ocean', 37.800, -46.517, 'routine sailing', 'brisk wind; light breeze', 'WN.W.', 'S.E.', JSON_ARRAY(), JSON_OBJECT(), 'made all sail.', 0, 0),
    (@voyage_albion_id, '1854-11-20 00:00:00', 'Atlantic Ocean (Outward)', 38.233, -45.333, 'lowered boats for exercise', 'light airs', '', '', JSON_ARRAY(), JSON_OBJECT('type','Finback','action','sightings','result',NULL), 'lowered all 4 boats for exercise.', 0, 0),
    (@voyage_albion_id, '1854-11-21 00:00:00', 'Atlantic Ocean (Outward)', 37.000, -43.000, 'lowered for blackfish; spoke ship', 'fair weather; brisk winds', 'SE; S[OUTHWAR]d', 'E. by S.', JSON_ARRAY(JSON_OBJECT('name','Spanish Frigate','home_port',NULL), JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT('type','Blackfish','action','lowered','result','no success'), 'signalized a Spanish Frigate; saw 2 other ships & a Finback; lowered 3 boats for Blackfish.', 0, 0),
    (@voyage_albion_id, '1854-11-26 00:00:00', 'Atlantic Ocean (Outward)', 34.367, -35.167, 'spoke ship; routine sailing', 'brisk wind; strong breeze', 'S.W.', 'S.E by S.; S.S.E.', JSON_ARRAY(JSON_OBJECT('name','Niagara (bark)','home_port','London')), JSON_OBJECT(), 'spoke English bark Niagara from Callao bound to London; 2 sails in sight.', 0, 0),
    (@voyage_albion_id, '1854-12-05 00:00:00', 'Atlantic Ocean (Cape Verde approach)', 24.500, -26.500, 'lowered for blackfish', 'fine weather; light breezes', 'N[ORTHWAR]d & W[ESTWAR]d', 'S. by W.', JSON_ARRAY(), JSON_OBJECT('type','Blackfish','action','lowered','result','no success'), 'lowered all 4 boats, but could not strike.', 0, 0),
    (@voyage_albion_id, '1854-12-10 00:00:00', 'Port of St. Vincent, Cape Verde', 16.890, -25.000, 'anchored; provisioning', 'light breezes; rainy', 'W.N.W.', '', JSON_ARRAY(), JSON_OBJECT(), 'came to anchor in Port _______ Island of St Vincent; all hands ashore on liberty (Civil a/c).', 0, 0),
    (@voyage_albion_id, '1854-12-11 00:00:00', 'Port of St. Vincent, Cape Verde', 16.890, -25.000, 'at anchor; provisioned', '', '', '', JSON_ARRAY(), JSON_OBJECT(), 'broke out for provisions; took the anchor shipped 5 Portuguese & took on board fowls, hogs, etc.', 0, 0),
    (@voyage_albion_id, '1854-12-12 00:00:00', 'Cape Verde Islands (Departure)', 16.890, -25.000, 'departed; routine sailing', 'fine weather; brisk trades', 'NE to EN.E.', 'S to E; S.W 1/2 S.', JSON_ARRAY(), JSON_OBJECT(), 'went to sea; Island of Bravo in sight.', 0, 0),
    (@voyage_albion_id, '1854-12-16 00:00:00', 'North Atlantic Ocean', 7.000, -27.000, 'whaling attempt', 'fine weather; light S.E. winds', 'S.E.', '', JSON_ARRAY(), JSON_OBJECT('type','Sperm whales','action','run off for','result','no success indicated'), 'Saw Sperm whales to leeward; 7 sails in sight.', 0, 0),
    (@voyage_albion_id, '1854-12-17 00:00:00', 'North Atlantic Ocean (Successful Whaling)', 6.650, -27.500, 'whaling — took whale', 'fine weather; light airs; squally later', '', '', JSON_ARRAY(), JSON_OBJECT('type','male whale','action','lowered & struck','result','successful'), 'lowered all 4 boats; struck one male whale; hove to & lay by the whale. Saw 4 sails & finback.', 0, 0),
    (@voyage_albion_id, '1854-12-19 00:00:00', 'North Atlantic Ocean (Boiling)', 5.500, -27.000, 'processing whale oil', 'overcast; moderate breezes; squalls', 'S[OUTHWAR]d & E[ASTWAR]d', 'larboard tack', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','boiling','barrels',16,'result','finished boiling & cooled down 16 Bbls'), 'started the fires; finished boiling; washed off ship.', 0, 0),
    (@voyage_albion_id, '1854-12-26 00:00:00', 'Near the Line, Atlantic Ocean (Successful Whaling)', 0.500, -29.000, 'whaling — took whale; spoke ship', 'fine weather; light breezes; moderate breezes', 'S.E to E; S[OUTHWAR]d & E[ASTWAR]d', 'larboard tack', JSON_ARRAY(JSON_OBJECT('name','Frances Jane (brig)','home_port','Baltimore')), JSON_OBJECT('type','male whale','action','saw & lowered & struck','result','successful'), 'saw sperm whales; lowered all 4 boats & struck one male whale; spoke brig Frances Jane from Baltimore for Pernambuco.', 0, 0),
    (@voyage_albion_id, '1854-12-28 00:00:00', 'Atlantic Ocean (Crossed the Line)', -0.700, -30.000, 'processing whale oil; spoke ship', 'fine weather; light breezes', 'S[OUTHWAR]d & E[ASTWAR]d', 'larboard tack', JSON_ARRAY(JSON_OBJECT('name','French bark','home_port',NULL)), JSON_OBJECT('type','whale oil','action','finished boiling','barrels',10,'result','finished & cooled down 10 Bbls'), 'crossed the line; signalized a French bark.', 0, 0),
    (@voyage_albion_id, '1855-01-04 00:00:00', 'South Atlantic Ocean', -18.000, -35.000, 'routine sailing; stowing oil', 'brisk winds; fine weather', 'E[ASTWAR]d', 'S.S.W.', JSON_ARRAY(), JSON_OBJECT(), 'stowed off the Main hold; painted the larboard boat.', 0, 0),
    (@voyage_albion_id, '1855-01-26 00:00:00', 'South Atlantic Ocean (Cape Horn approach)', -54.000, -62.667, 'routine sailing; gear setting', 'fresh gales; strong breezes', 'W. & W.S.W. to N.W.', 'S.S.W.', JSON_ARRAY(), JSON_OBJECT(), 'Under close reefed Fore Topsail & reefed Jib.', 0, 0),
    (@voyage_albion_id, '1855-01-27 00:00:00', 'Off Staten Land (Argentina)', -55.150, -64.750, 'sighted land; routine sailing', 'strong breezes; variable winds', 'N.W.', 'S. by W.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL), JSON_OBJECT('name','bark','home_port',NULL)), JSON_OBJECT(), 'saw Staten Land; running down the East side of Staten Land; 2 sails in company.', 0, 0),
    (@voyage_albion_id, '1855-01-28 00:00:00', 'Off Cape Horn', -56.650, -66.500, 'spoke ship; routine sailing', 'light breezes; heavy squalls', 'N[ORTHWAR]d & W[ESTWAR]d; S.W to W.', 'S.W by S.; S.S.W. to S.S.E.', JSON_ARRAY(JSON_OBJECT('name','Ocean Pearl (clipper ship)','home_port','Boston')), JSON_OBJECT(), 'spoke clipper ship Ocean Pearl bound for the Sandwich Islands.', 0, 0),
    (@voyage_albion_id, '1855-01-29 00:00:00', 'Off Cape Horn', -57.000, -67.500, 'whale sighted; porpoise chase', 'strong breezes; stiff breezes', 'SW to W; N.W.', 'starboard tack; S.W by W.', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','sightings','result','did not lower'), 'saw a right whale but going to windward; struck 2 porpoises & lost them.', 0, 0),
    (@voyage_albion_id, '1855-01-30 00:00:00', 'Off Cape Horn (Successful Whaling)', -57.500, -68.500, 'whaling — took whale; gear issue', 'strong breezes; thick & rainy', 'S.W. to S.S.E. to N[ORTHWAR]d', 'W by S 1/2 S.; WN.W.', JSON_ARRAY(), JSON_OBJECT('type','large sperm whales','action','saw & lowered & struck','result','successful'), 'parted the backrope & carried away the flying jib boom; saw several large sperm whales; lowered 3 boats, struck one of them.', 0, 0),
    (@voyage_albion_id, '1855-01-31 00:00:00', 'Off Cape Horn (Cutting In)', -57.500, -68.500, 'cutting in whale; spoke ships', 'strong winds; squally with rain', 'N[ORTHWAR]d & W[ESTWAR]d', 'lay by the whale', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT('type','sperm whale','action','cutting in','result','processing'), 'got the whale alongside; cutting in the body of the whale; saw 3 ships all outward bound. Starboard Boat...53 Bbls inferred (see Feb 2nd).', 0, 0),
    (@voyage_albion_id, '1855-02-01 00:00:00', 'Off Cape Horn (Boiling)', -57.817, -68.500, 'processing whale oil; spoke ship', 'rugged weather; strong breezes', 'N[ORTHWAR]d & W[ESTWAR]d; S.W.', 'W.N.W.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT('type','sperm whale','action','boiling','result','processing'), 'Cutting in the body of the whale & let go the head; started the works for boiling.', 0, 0),
    (@voyage_albion_id, '1855-02-06 00:00:00', 'Off Cape Horn', -57.500, -70.000, 'stowing oil; spoke ship', 'strong winds; moderate', 'W.S.W. to S.W.', 'N.W. to NN.W.; S[OUTHWAR]d', JSON_ARRAY(JSON_OBJECT('name','California','home_port','New Bedford')), JSON_OBJECT('type','sperm oil','action','stowed down','barrels',70,'result','on board'), 'Stowed down the sperm oil between decks; spoke ship California Manchester NB. Tacked to the S[OUTHWAR]d in company. 70 sperm (total).', 0, 0),
    (@voyage_albion_id, '1855-02-13 00:00:00', 'Off Cape Horn (Iceberg Sighted)', -56.633, -71.500, 'routine sailing', 'strong winds; hail squalls; strong from S.W.', 'W.S.W. to S.W.', 'N.W.; N.W by W.', JSON_ARRAY(), JSON_OBJECT(), 'passed a large iceberg to windw[ARD] from 2 to 300 feet high.', 0, 0),
    (@voyage_albion_id, '1855-02-17 00:00:00', 'South Pacific Ocean', -54.667, -78.333, 'spoke ship; routine sailing', 'brisk winds; moderate breezes', 'S.W. to W.N.W.', 'N.W.; N.N.W.', JSON_ARRAY(JSON_OBJECT('name','Vernon (bark)','home_port','New Bedford')), JSON_OBJECT(), 'spoke Bark Vernon. Gardner of N[EW] Bedford. 4 months out clean.', 0, 0),
    (@voyage_albion_id, '1855-02-28 00:00:00', 'South Pacific Ocean (Coast of Chile)', -42.967, -74.500, 'spoke ships; routine sailing', 'all sail breeze; thick foggy & rainy', 'WN.W. to S[OUTHWAR]d', 'N.; N.W. to N.E. to N.', JSON_ARRAY(JSON_OBJECT('name','Addison','home_port','New Bedford'), JSON_OBJECT('name','Falcon','home_port','New Bedford'), JSON_OBJECT('name','Anaconda (bark)','home_port','New Bedford'), JSON_OBJECT('name','Dominga (bark)','home_port','New Bedford')), JSON_OBJECT(), 'spoke ship Addison (1100 bbls 700 spm 400 wh); spoke Falcon (700 bound home).', 0, 0),
    (@voyage_albion_id, '1855-03-02 00:00:00', 'Off Mocha Island (Chile)', -38.167, -74.500, 'whaling attempt; provisioning', 'light airs; fine weather', 'S[OUTHWAR]d', 'N.N.W.', JSON_ARRAY(), JSON_OBJECT('type','humpbacks','action','saw & lowered','result','could not strike'), 'saw several humpbacks saw a swordfish; passed the island of Mocha.', 0, 0),
    (@voyage_albion_id, '1855-03-04 00:00:00', 'Talcahuano, Chile (Anchorage)', -36.717, -73.117, 'anchored; spoke ships', 'fine weather; light breezes', '', 'beating up the bay', JSON_ARRAY(JSON_OBJECT('name','Young Hero','home_port','Nantucket'), JSON_OBJECT('name','Courier','home_port','New Bedford'), JSON_OBJECT('name','Statira (bark)','home_port','New Bedford'), JSON_OBJECT('name','Balena','home_port','New Bedford'), JSON_OBJECT('name','Sappho (bark)','home_port','New Bedford'), JSON_OBJECT('name','Joshua Bragdon (bark)','home_port','New Bedford'), JSON_OBJECT('name','Pauline (bark)','home_port','New Bedford'), JSON_OBJECT('name','George & Susan','home_port','New Bedford'), JSON_OBJECT('name','Mercator (bark)','home_port','New Bedford'), JSON_OBJECT('name','Catawba','home_port','Nantucket'), JSON_OBJECT('name','Helen Snow (bark)','home_port','New Bedford'), JSON_OBJECT('name','Julian','home_port','New Bedford'), JSON_OBJECT('name','Eugenia (bark)','home_port','New Bedford'), JSON_OBJECT('name','Montgomery (bark)','home_port','New Bedford')), JSON_OBJECT(), 'came to anchor in Talcahuno. All hands ashore on liberty (Civil a/c).', 0, 0),
    (@voyage_albion_id, '1855-03-15 00:00:00', 'Talcahuano, Chile (Departure)', -36.717, -73.117, 'departed; routine sailing', 'fresh breezes; light winds', 'S[OUTHWAR]d', 'N.W by N.', JSON_ARRAY(JSON_OBJECT('name','Dartmouth (bark)','home_port','New Bedford')), JSON_OBJECT(), 'got under weigh & went to sea; in company with Bark Dartmouth.', 0, 0),
    (@voyage_albion_id, '1855-03-20 00:00:00', 'Near Felix & Ambrose Islands', -26.333, -80.000, 'fishing', 'moderate breezes; light squalls', 'S.S.E', 'N.W.; N.W. by W.', JSON_ARRAY(), JSON_OBJECT(), 'sent two boats in at Ambrose fishing caught about 100.', 0, 0),
    (@voyage_albion_id, '1855-03-28 00:00:00', 'South Pacific Ocean', -9.067, -93.117, 'spoke ship; routine sailing', 'all sails breeze', 'S.E to E.SE.', 'N.W by N.; N.W.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port','Hamburg')), JSON_OBJECT(), 'signalized a ship bound to the N.E. showing the Hamburg flag.', 0, 0),
    (@voyage_albion_id, '1855-04-04 00:00:00', 'South Pacific Ocean (Successful Whaling)', -1.200, -104.283, 'whaling — took blackfish', 'light breezes', 'E[ASTWAR]d', 'WN.W.', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','saw & lowered & struck & killed','result','successful'), 'saw blackfish lowered all 4 boats struck & killed one. W[AIST] B[OAT].', 0, 0),
    (@voyage_albion_id, '1855-04-10 00:00:00', 'South Pacific Ocean', 5.000, -109.000, 'whaling attempt', 'light breezes; variable winds', 'S[OUTHWAR]d & W[ESTWAR]d; S.E to S.W.', 'NW by W.; NW.', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','saw & lowered','result','could not strike'), 'saw blackfish lowered all 4 boats but could not strike.', 0, 0),
    (@voyage_albion_id, '1855-04-20 00:00:00', 'North Pacific Ocean', 16.333, -136.133, 'routine sailing', 'strong trades', 'EN.E.', 'W. by N.', JSON_ARRAY(), JSON_OBJECT(), 'saw piece of a ship''s rail.', 0, 0),
    (@voyage_albion_id, '1855-04-27 00:00:00', 'Off Maui & Molokai (Sandwich Islands)', 20.800, -157.500, 'coasting', 'moderate trades', '', 'W.', JSON_ARRAY(), JSON_OBJECT(), 'running down the N. side of Maui & Molokai, bound to Oahu.', 0, 0),
    (@voyage_albion_id, '1855-04-28 00:00:00', 'Honolulu, Oahu (Laying Off & On)', 21.300, -157.850, 'laying off & on; spoke ships', 'fine weather; moderate trades', '', '', JSON_ARRAY(JSON_OBJECT('name','Candace (bark)','home_port','New London'), JSON_OBJECT('name','Newton (bark)','home_port','New Bedford')), JSON_OBJECT(), 'lying off & on boat on shore; spoke B[AR]k Candace & B[AR]k Newton (6 mo[NTH]s 40 spm).', 0, 0),
    (@voyage_albion_id, '1855-05-04 00:00:00', 'North Pacific Ocean', 33.833, -168.533, 'spoke ship; routine sailing', 'fine weather; light winds', 'E[ASTWAR]d; S.E to E.', 'N.W by N.; N.W.', JSON_ARRAY(JSON_OBJECT('name','Ella Frances (bark)','home_port',NULL)), JSON_OBJECT(), 'spoke Bark Ella Frances 66 days from Newcastle for San Francisco.', 0, 0),
    (@voyage_albion_id, '1855-05-13 00:00:00', 'North Pacific Ocean (Approach to Aleutians)', 49.167, 179.833, 'routine sailing', 'fine weather; all sail breeze', 'S.E to E.', 'WN.W.; N.W by W.', JSON_ARRAY(), JSON_OBJECT(), 'heading WN.W; thick & rainy.', 0, 0),
    (@voyage_albion_id, '1855-05-17 00:00:00', 'Off Attu Island (Aleutians)', 52.050, 173.050, 'sighted land; heavy weather', 'fresh gales', 'S.W.', 'Western tack', JSON_ARRAY(), JSON_OBJECT(), 'saw the land to the N[ORTHWAR]d Island of Atou [ATTU].', 0, 0),
    (@voyage_albion_id, '1855-05-20 00:00:00', 'North Pacific Ocean (Right Whaling)', 54.500, 170.783, 'whaling attempt', 'moderate breezes; fine weather', 'N.W.; W.', 'N[ORTHWAR]d; WSW', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & chased','result','could not strike'), 'saw a right whale lowered 3 boats & chased but could not strike.', 0, 0),
    (@voyage_albion_id, '1855-05-21 00:00:00', 'North Pacific Ocean (Successful Whaling)', 55.000, 170.000, 'whaling — took whale', 'fine weather; light airs & calms', 'N.W.', 'WS.W.', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & struck & killed','result','successful'), 'saw a right whale; lowered 3 boats, struck & killed him. L. Boat...120 Bbls inferred (Next entry is cut in).', 0, 0);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1855-05-21 00:00:00', 'Kamchatka Approach (Cutting In)', 55.000, 170.000, 'cutting in whale; boiling prep', 'cloudy; light airs; strong winds later', 'S.W.', 'larboard tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','cutting in','result','finished cutting'), 'Finished cutting the whale (the 120 bbl whale).', 0, 0),
    (@voyage_albion_id, '1855-05-24 00:00:00', 'Kamchatka Approach (Boiling & Stowing)', 55.783, 167.233, 'finished boiling; stowing oil', 'strong breezes; moderate', 'N to N.N.E.', 'E[ASTWAR]d; N.W.', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','finished boiling & stowing','barrels',120,'result','120 bbls stowed'), 'finished boiling & cooled down; commenced stowing down oil. (70 spm + 120 wh total now)', 0, 0),
    (@voyage_albion_id, '1855-05-25 00:00:00', 'Kamchatka Approach', 56.250, 166.500, 'whaling attempt; made sail', 'overcast; light airs', 'N.E. to S[OUTHWAR]d', 'N.W.', JSON_ARRAY(), JSON_OBJECT('type','whales (bowhead implied)','action','saw & lowered & chased','result','no success'), 'saw whales lowered all 4 boats. noon took the boat up. D.R. position.', 0, 0),
    (@voyage_albion_id, '1855-05-29 00:00:00', 'Kamchatka Coasting', 57.400, 157.183, 'routine sailing', 'strong breezes; moderating', 'S[OUTHWAR]d; S[OUTHWAR]d & W[ESTWAR]d', 'E.S.E.; W.N.W.', JSON_ARRAY(), JSON_OBJECT('type','humpback','action','sightings','result',NULL), 'made sail to whole topsails. Saw humpback.', 0, 0),
    (@voyage_albion_id, '1855-05-31 00:00:00', 'Karaginsky Island (Approach)', 59.000, 163.000, 'inshore scouting; gear work', 'light airs & calms', 'S.W.', 'N.W by W.', JSON_ARRAY(), JSON_OBJECT('type','finbacks','action','sightings','result',NULL), 'land in sight; 2 boats went in shore to look for whales. Karaghinsky [KARAGINSKY] Island.', 0, 0),
    (@voyage_albion_id, '1855-06-01 00:00:00', 'Karaginsky Island (Grounding & Whaling Attempt)', 58.700, 162.800, 'went ashore (scouting); whaling attempt; struck rock', 'fine weather; light airs', 'W[ESTWAR]d; S[OUTHWAR]d; S.E.', 'W[ESTWAR]d; E[ASTWAR]d', JSON_ARRAY(), JSON_OBJECT('type','humpbacks','action','lowered','result','no success'), 'went on shore, found it full of humpbacks; the ship struck on the rocks ~ & remained fixed for about half an hour; tried the pumps found no damage.', 0, 0),
    (@voyage_albion_id, '1855-06-05 00:00:00', 'North Pacific Ocean (Right Whaling Attempt)', 60.533, 179.567, 'whaling attempt', 'light breezes; brisk winds later', 'NNE; W[ESTWAR]d; S.W.', 'N.; W[ESTWAR]d', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','saw & lowere & struck & drew iron','result','no success'), 'saw 2 right whales lowere all 4 boats struck & drew the iron L[ARBOARD] B[OAT].', 0, 0),
    (@voyage_albion_id, '1855-06-07 00:00:00', 'Off Cape Thaddery/Navarin (Anadyr)', 62.767, 179.800, 'spoke natives; provisioning', 'fine weather; light breezes; brisk winds later', 'E to S.E to S; SW.', 'N.N.E; N[ORTHWAR]d & E[ASTWAR]d', JSON_ARRAY(JSON_OBJECT('name','canoe/Indians','home_port','local')), JSON_OBJECT('type','killers','action','sightings','result',NULL), 'running along the land about Cape Navarin; a canoe came alongside with several Indians & traded a few things.', 0, 0),
    (@voyage_albion_id, '1855-06-09 00:00:00', 'Sea of Anadyr (Ice edge)', 63.617, -177.000, 'scouting ice; hunting', 'fine weather; light winds', 'N[ORTHWAR]d', 'W[ESTWAR]d; N.W.', JSON_ARRAY(), JSON_OBJECT('type','walrus','action','took one','result','successful'), 'stood in to the ice; went in with 2 boats. shot several ducks. took one walrus.', 0, 0),
    (@voyage_albion_id, '1855-06-13 00:00:00', 'Sea of Anadyr', 64.133, -174.000, 'scouting ice; saw dead whale', 'fine weather; light breezes; moderate breezes', 'S[OUTHWAR]d; S.W.', 'N.E by E.; S.E.', JSON_ARRAY(), JSON_OBJECT('type','dead whale (bowhead implied)','action','passed','result','fallen in & good for nothing'), 'passed the remains of a dead whale; stood in shore among the ice, but found no whales.', 0, 0),
    (@voyage_albion_id, '1855-06-14 00:00:00', 'Off St. Lawrence Island (Whaling Attempt)', 63.500, -170.000, 'whaling attempt; spoke natives', 'fine weather; light breezes; light airs & calms', 'W.; N.W.', 'E by N.; EN.E.', JSON_ARRAY(JSON_OBJECT('name','canoes/Indians','home_port','local')), JSON_OBJECT('type','bowheads','action','saw & lowered & chased','result','no success'), 'down the North side of St Lawrence Island; 7 canoes came alongside with about 50 Indians; saw several bowheads, lowered all 4 boats.', 0, 0),
    (@voyage_albion_id, '1855-06-16 00:00:00', 'St. Lawrence Island (Anchorage & Whaling)', 63.500, -170.000, 'anchored; inshore scouting; whaling attempt', 'light airs & calms; fine weather', 'W[ESTWAR]d; N.W.', 'inshore', JSON_ARRAY(JSON_OBJECT('name','canoes/Indians','home_port','local')), JSON_OBJECT('type','bowheads','action','chasing','result','chasing whales'), 'let go the stream anchor in 20 Fathoms; 4 boats chasing whales; 2 canoes with Indians came off to the ship.', 0, 0),
    (@voyage_albion_id, '1855-06-20 00:00:00', 'Near St. Lawrence Island', 63.000, -171.000, 'spoke ship; routine sailing', 'fine weather; light winds; light airs & calms', 'NN.W.; W[ESTWAR]d', 'W[ESTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Pfeil (schooner)','home_port','Honolulu')), JSON_OBJECT(), 'running to the W[ESTWAR]d between St Lawrence Island & the main; spoke Schooner Pfeil trading for walrus teeth, whalebone, skins etc.', 0, 0),
    (@voyage_albion_id, '1855-06-26 00:00:00', 'Sea of Anadyr (Sighted land/ice)', 64.833, -178.000, 'scouting; routine sailing', 'fog & light airs; fine weather later', 'S[OUTHWAR]d; W[ESTWAR]d; NW.', 'N.E.; N[ORTHWAR]d; WS.W.', JSON_ARRAY(), JSON_OBJECT('type','humpbacks','action','sightings','result',NULL), 'saw the land; ice in shore. saw humpbacks; steering WS.W. along shore.', 0, 0),
    (@voyage_albion_id, '1855-06-28 00:00:00', 'Sea of Anadyr', 64.000, -177.000, 'routine sailing; humpbacks seen', 'fine weather; some fog', 'W. to S.W.', 'S[OUTHWAR]d; S.E & SE by S.', JSON_ARRAY(), JSON_OBJECT('type','humpbacks','action','sightings','result',NULL), 'saw a number of humpbacks.', 0, 0),
    (@voyage_albion_id, '1855-07-03 00:00:00', 'Near Gore’s Island', 60.500, -174.500, 'sighted land; routine sailing', 'light breezes; moderate breezes', 'SS.E.; ESE.', 'N.E by E.; N.E.; S[OUTHWAR]d', JSON_ARRAY(), JSON_OBJECT('type','finback','action','sightings','result',NULL), 'saw the land Gore''s Island bearing E.N.E.; tacked off and inshore.', 0, 0),
    (@voyage_albion_id, '1855-07-04 00:00:00', 'Near Gore’s Island', 60.000, -174.000, 'heavy weather; routine sailing', 'fine weather; brisk winds; strong breeezes', 'ESE.; S[OUTHWAR]d', 'S[OUTHWAR]d; N.E.; S.E.', JSON_ARRAY(), JSON_OBJECT(), '79th anniversary of Independence; took in Mainsail Jib Fore & M[IZ]z[EN] Topsails.', 0, 0),
    (@voyage_albion_id, '1855-07-07 00:00:00', 'North Pacific Ocean (Successful Whaling)', 58.750, -173.500, 'whaling — took whale; cutting in', 'light breezes; strong winds later', 'N.W to W; S.E.', 'S.S.E.; E.S.E. tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & struck & killed','barrels',70,'result','successful'), 'saw a right whale lowered the boats, struck & killed him. L. Boat ~ 70 Bbls.', 0, 0),
    (@voyage_albion_id, '1855-07-09 00:00:00', 'North Pacific Ocean (Boiling & Cutting in Stinker)', 58.000, -173.000, 'boiling; cutting in dead whale', 'moderate breezes; light breezes', 'S[OUTHWAR]d; S.W.', 'WS.W. tack', JSON_ARRAY(), JSON_OBJECT('type','bowhead / dead whale','action','boiling & cutting in','result','much bloated & bone all gone'), 'saw a dead whale, lowered a boat & took him alongside. Cooled down got all ready for cutting.', 0, 0),
    (@voyage_albion_id, '1855-07-11 00:00:00', 'North Pacific Ocean (Finished Boiling)', 58.000, -173.000, 'finished boiling', 'light breeze; strong winds later', 'N.W.', 'under short sail', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','finished boiling','barrels',125,'result','finished boiling 125 bbls'), 'finished boiling 125 bbls.', 0, 0),
    (@voyage_albion_id, '1855-07-13 00:00:00', 'North Pacific Ocean (Lost Whale; Stowing)', 57.933, -175.000, 'whaling attempt; stowing oil', 'brisk winds; moderate breezes', 'S.E.; E to N.E.', 'EN.E tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & struck & cut lines','result','lost'), 'saw a right whale lowered all 4 boats, struck him. Cut off the lines & came on board; finished stowing off between decks etc.', 0, 0),
    (@voyage_albion_id, '1855-07-14 00:00:00', 'North Pacific Ocean (Successful Whaling)', 57.500, -175.500, 'whaling — took whale; cutting in', 'brisk winds; light winds; calms', 'ENE.', 'lay by', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & struck & killed','barrels',140,'result','successful'), 'struck a whale, killed him after a hard siege. L. Boat...140 Bbls.', 0, 0),
    (@voyage_albion_id, '1855-07-17 00:00:00', 'North Pacific Ocean (Boiling & Stowing)', 57.500, -175.500, 'boiling; whaling attempt; stowing oil', 'overcast; moderate breezes; thick fog', 'N[ORTHWAR]d; N.W.', 'under short sail', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','chasing; saw & lowered','barrels',145,'result','cooled down 145 Bbls'), 'cooled down 145 Bbls (presumably the July 14th whale); Stowing down oil in the Main hatchway.', 0, 0),
    (@voyage_albion_id, '1855-07-19 00:00:00', 'North Pacific Ocean (Successful Whaling)', 57.900, -175.333, 'whaling — took whale; cutting in', 'fine weather; light breezes; thick weather later', 'N[ORTHWAR]d; S[OUTHWAR]d & W[ESTWAR]d', 'lay by', JSON_ARRAY(), JSON_OBJECT('type','whale','action','struck & killed; cutting in','barrels',150,'result','successful'), 'struck the whale; got the larboard boat stove; killed him. W. Boat...150 Bbls.', 0, 0),
    (@voyage_albion_id, '1855-07-21 00:00:00', 'North Pacific Ocean (Boiling & Whaling Attempt)', 57.500, -174.000, 'boiling; spoke ship; whaling attempt', 'fine weather; strong winds', 'N[ORTHWAR]d & E[ASTWAR]d', 'N.E. tack', JSON_ARRAY(JSON_OBJECT('name','Asia (French Bark)','home_port','Harve')), JSON_OBJECT('type','right whale','action','saw & lowered','result','did not strike'), 'spoke French Bark Asia of Harve nothing this season; boiling etc.', 0, 0),
    (@voyage_albion_id, '1855-07-23 00:00:00', 'North Pacific Ocean (Finished Boiling & Stowing)', 57.500, -174.000, 'finished boiling; stowing oil', 'strong gales; light airs & calms', 'ENE.', 'S.E.', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','finished boiling & stowing','barrels',150,'result','cooled down 150 Bbls'), 'cooled down 150 Bbls (presumably the July 19th whale); Stowing down oil in the Fore Hold.', 0, 0),
    (@voyage_albion_id, '1855-07-25 00:00:00', 'North Pacific Ocean (Whaling Attempt & Scouting)', 58.000, -173.000, 'whaling attempt; scouting', 'light breezes; moderate breezes', 'E[ASTWAR]d; S[OUTHWAR]d & E[ASTWAR]d', 'NN.E tack', JSON_ARRAY(JSON_OBJECT('name','French bark','home_port',NULL)), JSON_OBJECT('type','right whale','action','saw & lowered','result','drove him to windward'), 'saw a right whale, lowered 3 boats in chase; French bark in sight to windward.', 0, 0),
    (@voyage_albion_id, '1855-07-29 00:00:00', 'North Pacific Ocean', 58.133, -172.500, 'whale sighting', 'thick weather with fog & rain; strong winds', 'S[OUTHWAR]d & E[ASTWAR]d', 'EN.E tack; S.E tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw','result',NULL), 'at noon saw a right whale.', 0, 0),
    (@voyage_albion_id, '1855-07-30 00:00:00', 'North Pacific Ocean (Whaling Attempts)', 58.000, -172.000, 'whaling attempt', 'strong winds; rugged with fog', 'S[OUTHWAR]d', 'S.E tack', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','lowered','result','could not strike'), 'lowered 3 boats in chase; saw several right whales; whale went to windward.', 0, 0),
    (@voyage_albion_id, '1855-08-01 00:00:00', 'North Pacific Ocean (Broken Iron & Gale)', 58.417, -173.000, 'whaling attempt; gale; hove to', 'strong winds; blowing a gale', 'S[OUTHWAR]d & E[ASTWAR]d', 'N.E. tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','lowered & struck & broke iron','result','lost'), 'lowered 3 boats. struck a whale & broke the iron.', 0, 0),
    (@voyage_albion_id, '1855-08-05 00:00:00', 'North Pacific Ocean (Lost Whale & Boat Damage)', 58.500, -173.000, 'whaling attempt; boat damage', 'light airs & calms; light airs', 'S.E.', '', JSON_ARRAY(), JSON_OBJECT('type','cow & calf (right whales)','action','lowered & struck','result','lost the whale; 3 boats stove'), 'saw right whales, lowered all 4 boats. Struck cow & calf; got 3 boats stove; lost the whale; the mate hurt.', 0, 0),
    (@voyage_albion_id, '1855-08-08 00:00:00', 'North Pacific Ocean (Whaling Attempts - Drawn Iron)', 58.200, -173.500, 'whaling attempts', 'overcast; moderate breezes; brisk winds', 'E[ASTWAR]d; N.E.', 'S[OUTHWAR]d; N.E.', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','lowered & struck & drew iron','result','no success'), 'lowered 3 boats ~ S[TARBOARD]. B[OAT]. struck a whale & drew the iron; struck one & drew the iron S[STARBOARD]. B[OAT].', 0, 0),
    (@voyage_albion_id, '1855-08-10 00:00:00', 'North Pacific Ocean (Spoke Ship)', 58.167, -174.000, 'whaling attempt; spoke ship; boiling', 'light breezes; thick fog', 'E[ASTWAR]d; SE.', '', JSON_ARRAY(JSON_OBJECT('name','Charles Carroll','home_port','New London')), JSON_OBJECT('type','right whales','action','lowered','result','could not strike'), 'spoke Ship Charles Carroll of New London 700 the season.', 0, 0),
    (@voyage_albion_id, '1855-08-13 00:00:00', 'North Pacific Ocean (Successful Whaling)', 57.900, -173.000, 'whaling — took whale; cutting in', 'fine weather; light airs & foggy; clear weather', 'W & WN.W; S[OUTHWAR]d & W[ESTWAR]d', 'E.', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','lowered & struck & killed','barrels',80,'result','successful'), 'lowered again struck a whale & drew the iron S[TARBOARD]. B[OAT]. struck another & killed him. L Boat (Capt)...80 Bbls.', 0, 0),
    (@voyage_albion_id, '1855-08-15 00:00:00', 'North Pacific Ocean (Successful Whaling & Spoke Ship)', 58.667, -173.467, 'whaling — took whale; spoke ship; cutting in', 'fine weather; moderate breezes', 'S[OUTHWAR]d; S[OUTHWAR]d & W[ESTWAR]d', 'lay by', JSON_ARRAY(JSON_OBJECT('name','Samuel Robertson','home_port','Fairhaven')), JSON_OBJECT('type','right whales','action','lowered & struck & killed','barrels',180,'result','successful'), 'spoke Ship Samuel Robertson Washburn of Fairhaven ~ 1200 this season; lowered 3 boats for right whales - struck one ~ & killed him. S. Boat...180 Bbls.', 0, 0),
    (@voyage_albion_id, '1855-08-16 00:00:00', 'North Pacific Ocean (Boiling & Lost Head)', 58.500, -173.500, 'finished cutting; boiling', 'moderate breezes; brisk winds; strong breezes', 'S[OUTHWAR]d & E[ASTWAR]d; E[ASTWAR]d; E.S.E', 'lay by', JSON_ARRAY(), JSON_OBJECT('type','whale; Killers','action','cutting in; boiling; saw Killers','result','lost the head & whalebone'), 'finished cutting in the whale - lost the head & whalebone; saw a school of Killers; boiling under double reefed topsails.', 0, 0),
    (@voyage_albion_id, '1855-08-20 00:00:00', 'North Pacific Ocean (Finished Boiling)', 58.500, -173.500, 'finished boiling', 'light airs & calms; foggy', 'N.E.', 'S by W.', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','cooled down','barrels',260,'result','cooled down 260 bbls'), 'cooled down 260 bbls (This volume is likely the combined oil from the Aug 13th and 15th whales: 80+180=260).', 0, 0),
    (@voyage_albion_id, '1855-08-27 00:00:00', 'North Pacific Ocean (Spoke Ship)', 58.333, -171.133, 'spoke ship; routine sailing', 'strong breezes; thick & rainy', 'S.E to S.', 'Eastern tack; E.S.E to S.E.', JSON_ARRAY(JSON_OBJECT('name','Newton (bark)','home_port','New Bedford')), JSON_OBJECT(), 'spoke Bark Newton, Sherman of N[EW] Bedford. 3 whales in season. (Total Oil: 70 spm + 750 wh - likely accumulated total by now).', 0, 0),
    (@voyage_albion_id, '1855-08-28 00:00:00', 'North Pacific Ocean (Spoke Ship & Gamming)', 58.000, -171.000, 'spoke ship; gamming; routine sailing', 'strong winds; brisk winds', 'SS.W; W.S.W; W[ESTWAR]d', 'S.E tack; S by E. & S.', JSON_ARRAY(JSON_OBJECT('name','Newton (bark)','home_port','New Bedford'), JSON_OBJECT('name','Montauk','home_port','Sag Harbor')), JSON_OBJECT(), 'gamming with the Newton; spoke Ship Montauk French of Sagharbor 1 whale the season.', 0, 0),
    (@voyage_albion_id, '1855-08-29 00:00:00', 'Near St. Paul’s Island (Pribilofs)', 57.500, -170.000, 'sighted land; routine sailing', 'strong breezes; thick weather', 'W.SW; S.W to W.S.W.', 'S by E & S.S.E', JSON_ARRAY(), JSON_OBJECT(), 'saw St Paul''s Island ahead. kept off & squared the yards running E.N.E.', 0, 0),
    (@voyage_albion_id, '1855-09-04 00:00:00', 'North of Fox Islands (Sighted Land)', 53.817, -172.133, 'routine sailing; sighted land', 'brisk all sail breeze; strong winds', 'NN.W; N.W; W.S.W.', 'S[OUTHWAR]d; W by S.', JSON_ARRAY(), JSON_OBJECT(), 'saw land to the SS.E. 5 PM saw another island; got up the larboard chain & bent to the anchor.', 0, 0),
    (@voyage_albion_id, '1855-09-06 00:00:00', 'Fox Islands Passage (Spoke Ship)', 52.800, -172.000, 'spoke ship; beating across passage', 'light breezes; all sail breeze', 'S.W; S[OUTHWAR]d', 'Western tack; S.S.E.', JSON_ARRAY(JSON_OBJECT('name','Oregon','home_port','Fairhaven')), JSON_OBJECT(), 'spoke Ship Oregon Eldridge, Fairhaven, 2 whales this season; beating across the passage.', 0, 0),
    (@voyage_albion_id, '1855-09-07 00:00:00', 'Fox Islands Passage (Heavy Weather)', 52.800, -172.000, 'hove to; gale', 'brisk winds; blowing a gale', 'S.E.', 'S.S.W. tack', JSON_ARRAY(), JSON_OBJECT(), 'lay to on the SS.W. tack with the main yard aback; blowing a gale from SE.', 0, 0),
    (@voyage_albion_id, '1855-09-09 00:00:00', 'Yunaska Island (Sighted Land)', 52.517, -171.550, 'sighted land; routine sailing', 'rugged weather; strong breezes; light winds', 'S to S.W; W to S.W.', 'S.E tack; S[OUTHWAR]d', JSON_ARRAY(), JSON_OBJECT(), 'close in with the land; Island of Younaska [YUNASKA] 8 miles distant.', 0, 0),
    (@voyage_albion_id, '1855-09-15 00:00:00', 'North Pacific Ocean (Bound to Sandwich Islands)', 41.333, -159.933, 'routine sailing', 'strong winds; moderate', 'S. to S.S.E.', 'S.E. tack; S.E by E.', JSON_ARRAY(), JSON_OBJECT(), 'heading S.E by E; set M[AIN]. T[OP]. G[ALLANT]. Sail & flying jib.', 0, 0),
    (@voyage_albion_id, '1855-09-17 00:00:00', 'North Pacific Ocean (Bound to Sandwich Islands)', 40.667, -153.917, 'routine sailing; provisioning prep', 'brisk winds; moderate breezes', 'S.S.E.', 'E.', JSON_ARRAY(), JSON_OBJECT(), 'employed mending Larboard Boat & breaking out Fore Hold for water.', 0, 0),
    (@voyage_albion_id, '1855-09-19 00:00:00', 'North Pacific Ocean (Bound to Sandwich Islands)', 40.217, -152.000, 'routine sailing', 'light airs & calms', 'S[OUTHWAR]d', 'E[ASTWAR]d; WS.W.', JSON_ARRAY(), JSON_OBJECT(), 'drying whalebone etc.', 0, 0);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1855-09-22 00:00:00', 'Pacific Ocean (Mid-latitudes)', 38.017, -151.650, 'spoke ship; routine sailing', 'light breezes', 'S[OUTHWAR]d; SS.W to S.W.', 'S.E. to S.S.E.', JSON_ARRAY(JSON_OBJECT('name','Tarquina (brig)','home_port',NULL)), JSON_OBJECT(), 'boarded brig Tarquina, 14 days from Oahu for Vancouver''s Island.', 0, 0),
    (@voyage_albion_id, '1855-09-25 00:00:00', 'Pacific Ocean (Bound to Sandwich Islands)', 32.517, -149.583, 'routine sailing', 'brisk winds', 'S.W. to W.S.W.', 'S.S.E.; S. by E.', JSON_ARRAY(), JSON_OBJECT(), 'mending old Main Top Sail; carrying all sail.', 0, 0),
    (@voyage_albion_id, '1855-10-05 00:00:00', 'Lahaina, Maui, Sandwich Islands (Anchorage)', 20.878, -156.685, 'sighted land; spoke ship; anchored', 'fine weather; light winds; light airs', 'SE to E', 'passage', JSON_ARRAY(JSON_OBJECT('name','Rambler','home_port','Nantucket')), JSON_OBJECT(), 'saw the land Maui & Molokoi; Spoke ship Rambler (1300 spm, 1400 the season); came to at Lahaina, Maui in 14 fathoms.', 0, 0),
    (@voyage_albion_id, '1855-10-13 00:00:00', 'Lahaina, Maui (Cargo Transfer)', 20.878, -156.685, 'provisioning; cargo transfer', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Rambler','home_port','Nantucket')), JSON_OBJECT(), 'Bundled the whalebone. shipped 19 Bundles on board the Rambler. took on board 23 bbls potatoes.', 0, 0),
    (@voyage_albion_id, '1855-10-15 00:00:00', 'Lahaina, Maui (Cargo Transfer)', 20.878, -156.685, 'provisioning; cargo transfer', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Rambler','home_port','Nantucket')), JSON_OBJECT(), 'shipped the bone on board the Rambler. 58 Bundles whalebone 6304 lbs.', 0, 0),
    (@voyage_albion_id, '1855-10-17 00:00:00', 'Lahaina, Maui (Anchorage Issue)', 20.878, -156.685, 'anchorage difficulty; minor damage', 'light air', 'S.E.', '', JSON_ARRAY(JSON_OBJECT('name','Newton (bark)','home_port','New Bedford')), JSON_OBJECT(), 'hove up the anchor...wind failing Came to anchor again...dragged the anchor & drifted foul of Bark Newton. did some damage to boats, davits etc.', 0, 0),
    (@voyage_albion_id, '1855-10-18 00:00:00', 'Lahaina, Maui (Departure)', 20.878, -156.685, 'departed', 'fine weather; moderate breezes', '', '', JSON_ARRAY(), JSON_OBJECT(), 'took the anchor with fine weather & moderate breezes & went to sea.', 0, 0),
    (@voyage_albion_id, '1855-10-19 00:00:00', 'Off Diamond Head, Oahu', 21.258, -157.800, 'laying off & on; captain ashore', 'fine weather; brisk winds', 'S[OUTHWAR]d', 'W.', JSON_ARRAY(), JSON_OBJECT(), 'lying aback off Diamond Head; run down for Honolulu. Capt[AIN] went ashore.', 0, 0),
    (@voyage_albion_id, '1855-10-21 00:00:00', 'Off Oahu (Departure)', 20.850, -158.433, 'captain returned; departed', 'fine weather; light winds', 'N[ORTHWAR]d', 'S.E by S.', JSON_ARRAY(), JSON_OBJECT(), 'Capt[AIN] came on board; made all sail...heading S.E by S. mended the Waist Boat etc.', 0, 0),
    (@voyage_albion_id, '1855-10-25 00:00:00', 'North Pacific Ocean (Southbound)', 11.983, -156.083, 'routine sailing; sail repair', 'strong trades; squalls', 'EN.E.', 'S.E by S.', JSON_ARRAY(), JSON_OBJECT(), 'total eclipse of the moon; split & unbent the Mainsail & bent another.', 0, 0),
    (@voyage_albion_id, '1855-10-31 00:00:00', 'Off Christmas Island', 1.867, -157.850, 'fishing; laying off & on', 'fine weather; light breezes', 'S.E.; S.S.E.', 'S.S.W.; E.N.E.', JSON_ARRAY(), JSON_OBJECT(), 'saw the land to SW.; 3 boats went in fishing etc.; lying off & on at Christmas Island.', 0, 0),
    (@voyage_albion_id, '1855-11-01 00:00:00', 'Off Christmas Island (Departure)', 1.000, -159.567, 'departed; smoked ship', 'fine weather; light breezes; all sail breeze', 'SS.E. to S.E.', 'S.W. tack', JSON_ARRAY(), JSON_OBJECT(), 'boats came on board; Smoked ship to kill rats.', 0, 0),
    (@voyage_albion_id, '1855-11-03 00:00:00', 'Near the Line (Crossed)', -0.500, -161.533, 'crossed the line; routine sailing', 'fine weather; light breezes', 'S[OUTHWAR]d; S.E.; E[ASTWAR]d', 'S.W. tack; SSW', JSON_ARRAY(), JSON_OBJECT(), 'Crossed the Line.', 0, 0),
    (@voyage_albion_id, '1855-11-06 00:00:00', 'South Pacific Ocean', -5.800, -161.617, 'routine sailing; gear work', 'light breezes; squally', 'E[ASTWAR]d; S[OUTHWAR]d', 'S to S.E.; E[ASTWAR]d', JSON_ARRAY(), JSON_OBJECT(), 'split the jib unbent it & bent another; saw white water.', 0, 0),
    (@voyage_albion_id, '1855-11-11 00:00:00', 'South Pacific Ocean (Spoke Ship)', -12.800, -158.317, 'spoke ship; routine sailing', 'light breezes; brisk all sail breeze', 'S.W.; N.W.; NN.W.', 'S.S.E. tack; S by E.', JSON_ARRAY(JSON_OBJECT('name','Europa','home_port','New Bedford')), JSON_OBJECT(), 'spoke Ship Europa (2300 / season); stood to S[OUTHWAR]d in Company.', 0, 0),
    (@voyage_albion_id, '1855-11-16 00:00:00', 'South Pacific Ocean', -21.500, -161.917, 'routine sailing; sail work', 'strong breezes', 'ESE.', 'S. & S by W.', JSON_ARRAY(), JSON_OBJECT(), 'bent & set Main & Main Topmast Staysail; employed mending Mainsail.', 0, 0),
    (@voyage_albion_id, '1855-11-17 00:00:00', 'South Pacific Ocean (Spoke Ship)', -23.700, -161.950, 'spoke ship; routine sailing', 'fine weather; all sail breeze', 'ES.E.; N.E.', 'S & S by W.', JSON_ARRAY(JSON_OBJECT('name','Europa','home_port','New Bedford')), JSON_OBJECT(), 'spoke ship Europa of New Bedford; Europa in Company.', 0, 0),
    (@voyage_albion_id, '1855-11-26 00:00:00', 'South Pacific Ocean (Right Whaling Sighting)', -39.233, -159.217, 'spoke ship; whaling attempt', 'strong winds; brisk winds', 'NW to W; WN.W.', 'NNE.', JSON_ARRAY(JSON_OBJECT('name','Neva (bark)','home_port','Greenport')), JSON_OBJECT('type','right whales','action','saw & lowered & chased','result','could not strike'), 'spoke Bark Neva of Greenport lying to with a right whale alongside; saw right whales, lowered 3 boats.', 0, 0),
    (@voyage_albion_id, '1855-12-05 00:00:00', 'South Pacific Ocean (Storm Damage)', -39.417, -141.183, 'gale; storm damage', 'heavy gales; heavy sea', 'S[OUTHWAR]d; S.W.', 'N.E.; EN.E & E by N.', JSON_ARRAY(), JSON_OBJECT(), 'blowing on a gale of wind from S[OUTHWAR]d; rolled over the Waist Boat & lost her. took in the Bow Boat.', 0, 0),
    (@voyage_albion_id, '1855-12-12 00:00:00', 'South Pacific Ocean', -38.833, -122.083, 'routine sailing; blackfish sighting', 'fine weather; light breezes; all sail breeze', 'S.S.E.; S.W. & W.S.W.', 'E & E by N.; E by S.', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','sightings','result',NULL), 'saw blackfish; set all the starboard studdingsails.', 0, 0),
    (@voyage_albion_id, '1855-12-18 00:00:00', 'Pacific Ocean (Chilean approach)', -43.800, -99.100, 'routine sailing; hunting', 'strong breezes; rugged', 'W to WN.W.; S.W.', 'E by S. & E.S.E.; E by N.', JSON_ARRAY(), JSON_OBJECT(), 'Caught a porpoise; reefed the Fore Topsail & furled the Mizzen.', 0, 0),
    (@voyage_albion_id, '1855-12-25 00:00:00', 'Off Coast of Chile (Christmas Day)', -44.383, -77.750, 'routine sailing; hunting; hove to', 'overcast; light breezes; light breezes', 'SS.W.; W[ESTWAR]d', 'E.N.E.; N.E.', JSON_ARRAY(), JSON_OBJECT(), 'Christmas Day; put out an old boat on the Waist cranes; Caught a porpoise; saw several finbacks.', 0, 0),
    (@voyage_albion_id, '1855-12-27 00:00:00', 'Near Guafo Island, Chile (Spoke Ship)', -43.333, -75.917, 'spoke ship; sighted land', 'fine weather; light breezes; moderate breezes', 'S.W.; N.W.', 'N.E.', JSON_ARRAY(JSON_OBJECT('name','Robert Edwards','home_port','New Bedford')), JSON_OBJECT(), 'saw the land to the E[ASTAWAR]d Island of Guafo; spoke ship Robert Edwards (950 spm).', 0, 0),
    (@voyage_albion_id, '1855-12-28 00:00:00', 'Near Guafo Island, Chile (Spoke Ship)', -43.000, -75.500, 'spoke ship; routine sailing', 'brisk winds; light airs', 'N.W.; W[ESTWAR]d', 'S.W. tack; N[ORTHWAR]d & E[ASTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Anaconda (bark)','home_port','New Bedford')), JSON_OBJECT('type','Blackfish & Finbacks','action','sightings','result',NULL), 'spoke Bark Anaconda (1200 spm); stood on the S.W tack in company.', 0, 0),
    (@voyage_albion_id, '1855-12-29 00:00:00', 'Coast of Chile (Gamming & Whaling Sighting)', -42.667, -75.250, 'gamming; routine sailing', 'light winds; fine weather', 'W[ESTWAR]d; WN.W.', 'Northern tack', JSON_ARRAY(JSON_OBJECT('name','Anaconda (bark)','home_port','New Bedford')), JSON_OBJECT('type','Sulphur bottoms','action','saw a great number','result',NULL), 'gamming with the Anaconda.', 0, 0),
    (@voyage_albion_id, '1855-12-31 00:00:00', 'Coast of Chile (Gear Damage)', -41.750, -74.500, 'whaling attempt; gear damage', 'moderate breezes; brisk winds', 'W.N.W.; W[ESTWAR]d', 'S.W. tack; N[ORTHWAR]d', JSON_ARRAY(), JSON_OBJECT('type','swordfish','action','lowered a boat','result','did not strike'), 'lowered a boat for a swordfish; in tacking carried away the Main Top gallant yard, sent down the wreck.', 0, 0),
    (@voyage_albion_id, '1856-01-03 00:00:00', 'Off Coast of Chile (Gale)', -41.650, -75.133, 'gale; hove to; moderating', 'strong gales; moderating', 'N[ORTHWAR]d', 'N.E by E.; W[ESTWAR]d; N.E.', JSON_ARRAY(), JSON_OBJECT(), 'lying to under close reefed Main Topsail & Spencers on the larboard tack.', 0, 0),
    (@voyage_albion_id, '1856-01-04 00:00:00', 'Off San Carlos, Chile (Sighted Land)', -41.800, -74.000, 'sighted land; routine sailing', 'strong winds', 'N. & N.N.W.', 'N.E. tack; S.E.', JSON_ARRAY(), JSON_OBJECT('type','finbacks','action','sightings','result',NULL), 'saw the land dist[ANT] ab[OU]t 10 miles; running down towards San Carlos.', 0, 0),
    (@voyage_albion_id, '1856-01-07 00:00:00', 'Coast of Chile', -38.833, -73.633, 'whaling sighting; routine sailing', 'fine weather; light breezes; strong breezes', 'WN.W to N.W.', 'NN.E.; W[ESTWAR]d', JSON_ARRAY(), JSON_OBJECT('type','humpback','action','saw','result',NULL), 'land in sight to leeward; saw a humpback.', 0, 0),
    (@voyage_albion_id, '1856-01-08 00:00:00', 'Off Mocha Island, Chile (Provisioning)', -38.383, -73.883, 'sighted land; boat ashore', 'moderate breezes; fine weather', 'N.W.; S.W.; S.E.; S[OUTHWAR]d', 'NN.W.; N.W.', JSON_ARRAY(), JSON_OBJECT(), 'saw Mocha bearing N.W kept up for it; boat went ashore; Fine weather & brisk winds.', 0, 0),
    (@voyage_albion_id, '1856-01-10 00:00:00', 'Talcahuano, Chile (Anchorage)', -36.717, -73.117, 'anchored; spoke ships', 'fine weather; light airs & variables', 'S[OUTHWAR]d', 'NN.W.', JSON_ARRAY(JSON_OBJECT('name','Julian','home_port','Nantucket'), JSON_OBJECT('name','Mary','home_port','New London'), JSON_OBJECT('name','Corea','home_port','New Bedford'), JSON_OBJECT('name','Hydaspe (bark)','home_port','New Bedford')), JSON_OBJECT(), 'came to anchor in Talchuano; set anchor watches. Arrived Ship Scotland.', 0, 0),
    (@voyage_albion_id, '1856-01-22 00:00:00', 'Talcahuano, Chile (Cargo Transshipment)', -36.717, -73.117, 'cargo transshipment; provisioning', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Hydaspe (bark)','home_port','New Bedford')), JSON_OBJECT(), 'hauled alongside the Bark Hydaspe put on 14 hired men & commenced discharging oil into her.', 0, 0),
    (@voyage_albion_id, '1856-01-26 00:00:00', 'Talcahuano, Chile (Cargo Transshipment Finished)', -36.717, -73.117, 'finished cargo transshipment; provisioning', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Hydaspe (bark)','home_port','New Bedford')), JSON_OBJECT(), 'Finished discharging oil; Oil shipped on board the Hydaspe 17801 gallons whale & 805 sperm...590 Bbls ~ 21 gallons.', 0, 0),
    (@voyage_albion_id, '1856-01-31 00:00:00', 'Talcahuano, Chile (Departure Prep)', -36.717, -73.117, 'departure prep; crew issue', '', 'S.E.', '', JSON_ARRAY(), JSON_OBJECT(), '3 men missing...the Bow Boat with them; news this morning that the boat...has been picked up about 150 miles from here, bottom up.', 0, 0),
    (@voyage_albion_id, '1856-02-01 00:00:00', 'Talcahuano, Chile (Departure)', -34.850, -75.017, 'departed; routine sailing', 'light winds; strong breezes', 'S.E.; S.S.E.', 'WN.W.; N.W by W. & N.W.', JSON_ARRAY(), JSON_OBJECT(), 'took the anchor with light winds...and went to sea; unbent chains etc; employed fitting boats, craft etc.', 0, 0),
    (@voyage_albion_id, '1856-02-06 00:00:00', 'Off Ambrose Island (Whaling Attempt)', -21.833, -82.217, 'whaling attempt; routine sailing', 'rugged weather; strong breezes', 'S.E.', 'NN.W.; N.W by N.', JSON_ARRAY(), JSON_OBJECT('type','sperm whales','action','saw & gallied & lowered & chased','result','without success'), 'saw sperm whales, gallied them with the Ship, lowered all 4 boats in chase.', 0, 0),
    (@voyage_albion_id, '1856-02-17 00:00:00', 'South Pacific Ocean', -18.700, -107.183, 'routine sailing; hunting', 'fine weather; all sail breeze', 'E[ASTWAR]d', 'W by S.', JSON_ARRAY(), JSON_OBJECT(), 'Caught a porpoise; running W & W by S.', 0, 0),
    (@voyage_albion_id, '1856-03-01 00:00:00', 'Hanaiapa Bay, Dominica (Anchorage)', -9.742, -139.060, 'sighted land; anchored; provisioning', 'fine weather; all sail breeze', 'E[ASTWAR]d', 'N.W.; N.W by W.', JSON_ARRAY(JSON_OBJECT('name','Bark Richmond','home_port','New Bedford')), JSON_OBJECT('type','blackfish','action','saw school','result',NULL), 'saw land probably Ariadne Rock; saw Oneeteara [MOTANE] or St Pedro''s Island ahead...came to anchor. at Dominica...bay called Hanaiapa.', 0, 0),
    (@voyage_albion_id, '1856-03-06 00:00:00', 'Hanaiapa Bay, Dominica (Spoke Ship)', -9.742, -139.060, 'provisioning; spoke ship', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Richmond (bark)','home_port','New Bedford')), JSON_OBJECT(), 'Took on board 1 boatload of wood; sent a boat out & boarded Bark Richmond (500 Bbls sperm, lying off & on).', 0, 0),
    (@voyage_albion_id, '1856-03-08 00:00:00', 'Hanaiapa Bay, Dominica (Departure)', -9.742, -139.060, 'departed', 'light airs', '', '', JSON_ARRAY(), JSON_OBJECT(), 'took the anchor with light airs. put the boat ahead & towed out.', 0, 0),
    (@voyage_albion_id, '1856-03-10 00:00:00', 'Off Dominica (Trading)', -9.800, -139.000, 'laying to; trading', 'fine weather; light breezes', 'E[ASTWAR]d', 'E[ASTWAR]d', JSON_ARRAY(), JSON_OBJECT(), 'cleared the weather end of the land. hauled aback & hove to; sent boat in at the bay of Hanamate to trade.', 0, 0),
    (@voyage_albion_id, '1856-03-15 00:00:00', 'Off Nuku Hiva (Spoke Ship)', -8.900, -140.017, 'sighted land; spoke ship; trading', 'fine weather; light breezes', 'EN.E.', 'N.W by W; N.W.', JSON_ARRAY(JSON_OBJECT('name','Richmond (bark)','home_port','New Bedford')), JSON_OBJECT(), 'run down the S. side of Nooaheva [NUKU HIVA]; spoke Bark Richmond; landed the white man.', 0, 0),
    (@voyage_albion_id, '1856-03-16 00:00:00', 'Marquesas Islands (Departure)', -7.600, -141.350, 'sighted land; departed', 'fine with all sail breeze', 'E[ASTWAR]d; EN.E.', 'WN.W.; NN.W.', JSON_ARRAY(), JSON_OBJECT(), 'saw Mottuaty[?] bearing NW by W; lost sight of all land.', 0, 0);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1856-03-17 00:00:00', 'Pacific Ocean (Northbound)', -5.333, -142.050, 'routine sailing; boat repair', 'fine weather; all sail breeze; light breezes', 'E[ASTWAR]d; EN.E. to N.E.', 'NN.W.', JSON_ARRAY(), JSON_OBJECT(), 'employed mending Bow Boat etc.', 0, 0),
    (@voyage_albion_id, '1856-03-20 00:00:00', 'Pacific Ocean (Equator Approach)', 0.250, -144.967, 'routine sailing; boat work', 'fine weather; light breezes', 'N.E. & EN.E.', 'N. by W.', JSON_ARRAY(), JSON_OBJECT(), 'employed mending Waist Boat painted the Bow Boat etc.', 0, 0),
    (@voyage_albion_id, '1856-03-24 00:00:00', 'Pacific Ocean', 7.733, -148.183, 'routine sailing; gear mending', 'brisk winds; squally', 'N.E to NN.E.', 'NN.W. to N.W.', JSON_ARRAY(), JSON_OBJECT('type','diamond fish & shark','action','sightings','result',NULL), 'unbent & mended the Spanker.', 0, 0),
    (@voyage_albion_id, '1856-03-28 00:00:00', 'Pacific Ocean (Northbound)', 14.133, -156.617, 'routine sailing; spoke ship', 'brisk trades', 'N.E.', 'W.N.W.; N.W by W.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT(), 'at daylight saw a ship heading to the S[OUTHWAR]d.', 0, 0),
    (@voyage_albion_id, '1856-04-05 00:00:00', 'North Pacific Ocean (Successful Whaling)', 26.500, -176.383, 'whaling — took whale; cutting in', 'fine weather; light breezes', 'E & ESE.', 'WN.W.', JSON_ARRAY(), JSON_OBJECT('type','right whales (cow & calf)','action','saw & lowered & struck & saved','barrels_cow',140,'barrels_calf',15,'result','successful'), 'saw right whales! lowered all boats. Struck cow & calf. & saved both. L.B. 140 ... 15.', 0, 0),
    (@voyage_albion_id, '1856-04-06 00:00:00', 'North Pacific Ocean (Cutting & Boiling Prep)', 26.183, -177.333, 'cutting in; boiling prep', 'light airs; light breezes; squalls', 'E[ASTWAR]d; S[OUTHWAR]d & E[ASTWAR]d', 'WN.W.', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','finished cutting','result','finished cutting in the large whale & cut the small one'), 'finished cutting in the large whale & cut the small one; Started the fires for boiling.', 0, 0),
    (@voyage_albion_id, '1856-04-09 00:00:00', 'North Pacific Ocean (Finished Boiling)', 29.333, 178.833, 'finished boiling; stowing prep', 'fine weather; light winds', 'E[ASTWAR]d', 'N.W.; W.N.W.', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','finished boiling & cooled down','barrels',155,'result','finished boiling & cooled down. 155 Bbls'), 'finished boiling & cooled down. 155 Bbls.', 0, 0),
    (@voyage_albion_id, '1856-04-14 00:00:00', 'North Pacific Ocean (Lost Whale - Sunk)', 32.667, 170.417, 'whaling — lost whale', 'fine weather; moderate breezes', 'S[OUTHWAR]d & E[ASTWAR]d', 'N.W.', JSON_ARRAY(), JSON_OBJECT('type','right whales (2 large)','action','lowered & struck 2 & cut line from 1 & sunk 1','result','Killed & sunk the other one'), 'struck 2 large whales. got foul lines. Cut from one whale. Killed & sunk the other one. W.B. ... sunk.', 0, 0),
    (@voyage_albion_id, '1856-04-16 00:00:00', 'North Pacific Ocean (Spoke Schooner)', 35.167, 171.333, 'spoke ship; sail work; heavy weather', 'brisk winds; strong winds; thick weather', 'S.S.E.; S.E.', 'N.; NN.W.', JSON_ARRAY(JSON_OBJECT('name','Pfeil (schooner)','home_port',NULL)), JSON_OBJECT(), 'fished the Fore yard; spoke schooner Pfeil bound to Honolulu.', 0, 0),
    (@voyage_albion_id, '1856-04-29 00:00:00', 'Off Kamchatka (Ice Encounter/Sighted Land)', 55.200, 164.367, 'ice encountered; sighted land; routine sailing', 'strong winds; hail squalls; clear weather', 'N.E.; W[ESTWAR]d', 'N.N.W.; E.S.E.', JSON_ARRAY(), JSON_OBJECT(), 'saw a field of ice...ran in among pieces; saw the land. Coast of Kanitskatka.', 0, 0),
    (@voyage_albion_id, '1856-05-02 00:00:00', 'Off Bering Island (Spoke Ship)', 55.183, 165.317, 'ice encounter; spoke ship', 'moderate breezes; light winds; freezing weather', 'W.S.W.; N.W.', 'S.E by S.; S.W. tack', JSON_ARRAY(JSON_OBJECT('name','William C. Nye','home_port','New Bedford')), JSON_OBJECT(), 'ran into the ice...wore off; spoke ship William C. Nye (700 wh. 400 spm. nothing this season).', 0, 0),
    (@voyage_albion_id, '1856-05-05 00:00:00', 'Off Kamchatka (Spoke Ships & Whaling Attempt)', 53.083, 166.167, 'spoke ships; whaling attempt', 'brisk winds; light airs; light breezes', 'N[ORTHWAR]d; S to S.E.', 'E.; N[ORTHWAR]d & E[ASTWAR]d', JSON_ARRAY(JSON_OBJECT('name','James D. Thompson (bark)','home_port','New Bedford'), JSON_OBJECT('name','William C. Nye','home_port','New Bedford')), JSON_OBJECT('type','right whale','action','saw & lowered & chased','result','could not strike'), 'spoke Bark James D. Thompson (clean); saw a right whale, lowered all 4 boats in chase.', 0, 0),
    (@voyage_albion_id, '1856-05-08 00:00:00', 'Off Copper Island (Sighted Land)', 54.750, 169.500, 'sighted land; routine sailing', 'brisk winds; light breezes', 'S[OUTHWAR]d & E[ASTWAR]d', 'N & N by E.', JSON_ARRAY(), JSON_OBJECT(), 'saw Copper Island to the N.W. dist[ANT] 30 miles.', 0, 0),
    (@voyage_albion_id, '1856-05-11 00:00:00', 'Off Kamchatka (Ice Encounter & Spoke Ships)', 58.000, 169.000, 'ice encounter; spoke ships', 'fresh gales; moderate; light breezes', 'E.N.E.; E[ASTWAR]d', 'Northern tack; S.E.', JSON_ARRAY(JSON_OBJECT('name','Agate (brig)','home_port','San Francisco'), JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT(), 'spoke Brig Agate (no oil); Midnight ran into the ice; wore off to S[OUTHWAR]d; spoke Ship Japan (50 sperm).', 0, 0),
    (@voyage_albion_id, '1856-05-13 00:00:00', 'Kamchatka Cruising (Heavy Ice)', 58.667, 167.150, 'ice encounter; routine sailing', 'strong winds; blowing on a gale', 'E to N.E.', 'S.E to ES.E.', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT(), 'ran in among heavy ice; Japan in company.', 0, 0),
    (@voyage_albion_id, '1856-05-24 00:00:00', 'Kamchatka Sea (Whaling Attempt)', 55.633, -171.250, 'whaling attempt; routine sailing', 'overcast; light breezes; thick & rainy', 'N.E; E[ASTWAR]d; S.E.', 'ES.E.; Northern tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered','result','did no strike'), 'saw right whale. lowered all 4 boats.', 0, 0),
    (@voyage_albion_id, '1856-05-27 00:00:00', 'Near Unalaska/Pillar Rock (Sighted Land)', 54.467, -166.567, 'sighted land; routine sailing', 'overcast; moderate breezes; brisk breezes', 'S[OUTHWAR]d & W[ESTWAR]d; S[OUTHWAR]d', 'S.E.; E by N.; N.E.', JSON_ARRAY(), JSON_OBJECT('type','humpbacks','action','saw several','result',NULL), 'saw Pillar Rock bearing SS.E. dist[ANT] 20 miles; saw the north part of the Island of Oonalashka.', 0, 0),
    (@voyage_albion_id, '1856-05-28 00:00:00', 'Near Unalaska (Whaling Attempt)', 55.133, -165.733, 'whaling attempt; routine sailing', 'fine weather; all sail breeze', 'S[OUTHWAR]d', 'N.N.E.; N.W by N.; EN.E.', JSON_ARRAY(), JSON_OBJECT('type','right whale?','action','lowered & chased','result','did not strike'), 'saw great number of finbacks, 1 right whale?; lowered all 4 boats. in chase.', 0, 0),
    (@voyage_albion_id, '1856-05-30 00:00:00', 'Near Unimak/Alaska Peninsula (Spoke Ship)', 55.800, -165.500, 'spoke ship; gale; hove to', 'strong breezes; thick & foggy; strong gales', 'S.E.; S.W.', 'E.N.E. tack; S.E tack', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT(), 'spoke ship Japan...nothing since we saw her last; blowing on a gale from S.W. lying to.', 0, 0),
    (@voyage_albion_id, '1856-05-31 00:00:00', 'Off Unimak/Alaska Peninsula (Humpback Sightings)', 55.000, -163.500, 'sighted land; routine sailing', 'strong gales; strong breezes', 'S..W.; W.S.W.', 'S.S.E.', JSON_ARRAY(), JSON_OBJECT('type','humpbacks','action','saw multitudes','result',NULL), 'saw the land. Island of Oonemak [UNIMAK] ahead; coast of the main land peninsula of ALaska.', 0, 0),
    (@voyage_albion_id, '1856-06-02 00:00:00', 'Bristol Bay (Whaling Attempt)', 57.000, -163.000, 'whaling attempt; gale', 'brisk winds; thick & rainy; strong breezes', 'S.E to S.S.E.; S.W.', 'N[ORTHWAR]d & W[ESTWAR]d; N[ORTHWAR]d & E[ASTWAR]d', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered','result','could not strike'), 'saw right whale, lowered all 4 boats in chase.', 0, 0),
    (@voyage_albion_id, '1856-06-04 00:00:00', 'Bristol Bay', 56.433, -164.467, 'whaling sighting; routine sailing', 'light breezes; strong breezes', 'W[ESTWAR]d; S[OUTHWAR]d; SS.W.', 'W.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT('type','right whale?','action','saw','result','did not lower'), 'saw a right whale? going quick to windward.', 0, 0),
    (@voyage_albion_id, '1856-06-08 00:00:00', 'Near Unimak/Akun Islands (Successful Whaling)', 54.667, -166.150, 'whaling — took whale; cutting prep', 'clear weather; light breezes; brisk winds', 'S.W.; W[ESTWAR]d', 'S[OUTHWAR]d', JSON_ARRAY(), JSON_OBJECT('type','right whales (cow & calf)','action','lowered & struck cow & calf & killed both','barrels_cow',0,'barrels_calf',25,'result','killed both; left the calf to save the cow; calf sunk'), 'saw right whales, lowered all 4 boats. struck cow & calf. killed both, left the calf to save the cow. L. Boat 25 ... sunk (calf).', 0, 0),
    (@voyage_albion_id, '1856-06-09 00:00:00', 'Near Akun/Akutan Islands (Found Dead Calf)', 54.500, -166.500, 'cutting in dead whale (calf)', 'clear weather; fine weather; light breezes', 'W to N.W.', 'S[OUTHWAR]d', JSON_ARRAY(), JSON_OBJECT('type','dead calf (right whale)','action','saw & took alongside & cut in','result','proved to be the Calf we killed day before yesterday; finished cutting'), 'saw a dead whale...proved to be the Calf we killed day before yesterday; finished cutting.', 0, 0),
    (@voyage_albion_id, '1856-06-11 00:00:00', 'Near Fox Islands (Finished Boiling & Spoke Ship)', 55.317, -167.500, 'finished boiling; spoke ship', 'moderate breezes; brisk winds; rugged', 'S.W.; SS.W.; S[OUTHWAR]d', 'S.E. tack; W[ESTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT('type','whale oil','action','cooled down','barrels',25,'result','cooled down 25 Bbls'), 'cooled down 25 Bbls (calf oil). Japan has struck & lost a whale.', 0, 0),
    (@voyage_albion_id, '1856-06-16 00:00:00', 'Near Unalaska (Whaling Attempt)', 54.500, -167.000, 'stowing oil; whaling attempt', 'light breezes; light airs & calms', 'N[ORHWAR]d; S[OUTHWAR]d & E[ASTWAR]d', 'E.N.E.; N.W. tack', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','lowered & chased','result','could not strike'), 'stowed down the oil; saw right whales going quick. at noon lowered all 4 boats in chase.', 0, 0),
    (@voyage_albion_id, '1856-06-19 00:00:00', 'Near Fox Islands (Gale & Hove To)', 55.400, -167.500, 'whaling attempts; gale; hove to', 'light airs & calms; strong winds; strong gales', 'W.S.W.; S. E.; E.S.E.', 'N.W. tack; NN.E. to N.E.', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered','result','did not strike'), 'hove to under Mail Topsail & Spencers; took in Main Topsail & lay to under Spencers & F[ORE]. T[OP]. Staysail.', 0, 0),
    (@voyage_albion_id, '1856-06-23 00:00:00', 'Near Unalaska (Spoke Ship & Whaling Attempt)', 56.667, -166.400, 'spoke ship; whaling attempt', 'strong breezes; thick & clear by spells', 'W[ESTWAR]d', 'E by N.; N.W.', JSON_ARRAY(JSON_OBJECT('name','French bark (prob. Asia)','home_port','Harve')), JSON_OBJECT('type','right whale','action','lowered & chased','result','could not strike'), 'signalized a French bark probably the Asia of Harve; saw right whale. lowered 3 boats and chased.', 0, 0),
    (@voyage_albion_id, '1856-06-25 00:00:00', 'Bristol Bay (Sounding & Scouting)', 57.833, -169.000, 'sounding; fishing; routine sailing', 'foggy; light breezes', 'S. & SSE.; S[OUTHWAR]d & E[ASTWAR]d', 'WN.W.; E by N.; N by W.', JSON_ARRAY(), JSON_OBJECT(), 'sounded in 60 fathoms; lowered a boat for fish. Caught nothing.', 0, 0),
    (@voyage_albion_id, '1856-06-27 00:00:00', 'Off St. Paul''s Island (Successful Whaling)', 57.667, -169.767, 'whaling — took whale; cutting in', 'fine weather; light airs; light breezes', 'S.S.E.; E[ASTWAR]d; S.W to W.', 'S.W.', JSON_ARRAY(), JSON_OBJECT('type','bowheads (2)','action','saw & lowered & struck & killed','barrels',70,'result','successful'), 'saw 2 bowheads, lowered the boats, struck one of them Killed him and took him alongside. B.B. ... 70.', 0, 0),
    (@voyage_albion_id, '1856-06-28 00:00:00', 'Off St. Paul''s Island (Successful Whaling)', 57.667, -169.767, 'whaling — took whale; cutting in; boiling prep', 'light breezes; light airs', 'W[ESTWAR]d; S[OUTHWAR]d', 'SS.W. tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & struck & killed','barrels',70,'result','successful'), 'saw a right whale. lowered one boat. Struck him, lowered the other boats, killed & took him alongside. L.B. ... 70.', 0, 0),
    (@voyage_albion_id, '1856-07-03 00:00:00', 'Off Fox Islands (Finished Boiling)', 55.500, -169.000, 'finished boiling; stowing oil', 'strong breezes', 'WS.W.', 'S.E. tack; S to SS.E.', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','finished stowing down','barrels',135,'result','finished stowing down. 135 Bbls'), 'finished stowing down. saw a finback. (135 Bbls) - likely a combined amount from the two successful whales.', 0, 0),
    (@voyage_albion_id, '1856-07-15 00:00:00', 'Near Fox Islands (Boiling & Spoke Ships)', 56.500, -165.500, 'boiling; spoke ships; whaling sightings', 'fine weather; moderate breezes; rainy weather', 'S[OUTHWAR]d & W[ESTWAR]d; W[ESTWAR]d', 'N.W.', JSON_ARRAY(JSON_OBJECT('name','Braganza','home_port','New Bedford'), JSON_OBJECT('name','William C. Nye','home_port','New Bedford')), JSON_OBJECT('type','right whales','action','chasing & sightings','result','cooled down 40 Bbls'), '7 ships in sight; spoke a boat of Ship Braganza; finished boiling & cooled down. 40 Bbls (likely the cow from June 8th).', 0, 0),
    (@voyage_albion_id, '1856-07-16 00:00:00', 'Near Fox Islands (Spoke Ships)', 56.267, -165.067, 'spoke ships; routine sailing', 'fine weather; light breezes', 'W.N.W.; W[ESTWAR]d', 'E[ASTWAR]d; NN.W.', JSON_ARRAY(JSON_OBJECT('name','Good Return','home_port','New Bedford'), JSON_OBJECT('name','Callao','home_port','New Bedford')), JSON_OBJECT(), 'spoke ship Good Return (2 whales alongside); spoke a boat of Ship Callao (lying by a sunken whale).', 0, 0),
    (@voyage_albion_id, '1856-07-19 00:00:00', 'Near Fox Islands (Stowing Oil)', 56.167, -167.350, 'stowing oil; hove to', 'thick & rainy weather; moderate breeze', 'S.E to S.W.; W[ESTWAR]d', 'Southern tack', JSON_ARRAY(), JSON_OBJECT(), 'stowed down the large [FARE?] of oil, 36 Bbls in the Main hatchway.', 0, 0),
    (@voyage_albion_id, '1856-07-25 00:00:00', 'Near Fox Islands (Spoke Ship)', 55.833, -163.800, 'spoke ship; routine sailing', 'fine weather; light breezes; thick, rainy weather', 'S to S.E.', 'W.; S.W.; N. E by E.', JSON_ARRAY(JSON_OBJECT('name','Salamandre (French Bark)','home_port','Harve')), JSON_OBJECT(), 'spoke French Bark Salamandre...nothing this season; gammed with the Salamandre.', 0, 0),
    (@voyage_albion_id, '1856-07-26 00:00:00', 'Bristol Bay (Lost Whale - Sunk)', 57.000, -163.000, 'whaling — lost whale; spoke ship', 'thick & rainy weather; strong breezes', 'S[OUTHWAR]d', 'N[ORTHWAR]d; S.E tack; NN.W.', JSON_ARRAY(JSON_OBJECT('name','Salamandre (French Bark)','home_port','Harve'), JSON_OBJECT('name','Callao','home_port','New Bedford')), JSON_OBJECT('type','right whale','action','lowered & struck & killed & sunk','result','sunk him to windward of the ship'), 'spoke Ship Callao (cutting a right whale); saw right whale, lowered all 4 boats, struck & killed & sunk him to windward.', 0, 0),
    (@voyage_albion_id, '1856-07-27 00:00:00', 'Bristol Bay (Lost Whale - Cut Off)', 57.000, -163.000, 'lost whale; whaling attempt', 'strong winds; strong gales', 'S[OUTHWAR]d; SSW.', 'Wesern tack; S.E.', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','held on to whale & cut off lines; lowered','result','Cut off & came on board'), 'held on to the whale 4 PM blowing on fresh...Cut off & came on board; saw several right whales. lowered from S[OUTHWAR]d & heavy swell in chase.', 0, 0),
    (@voyage_albion_id, '1856-07-28 00:00:00', 'Bristol Bay (Lost Whale - Cut Lines)', 57.000, -163.000, 'whaling attempt; lost whale', 'light breezes; thick fog', 'S[OUTHWAR]d & W[ESTWAR]d', 'Eastern tack; W.S.W.', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','struck & held on til dark & cut lines','result','struck another. held on til dark. thus in thick fog. cut the lines & came on board'), 'struck another. held on til dark. thus in thick fog. cut the lines & came on board.', 0, 0),
    (@voyage_albion_id, '1856-07-29 00:00:00', 'Bristol Bay (Spoke Ship & Whaling Attempt)', 57.000, -163.000, 'spoke ship; whaling attempt', 'light breezes; moderate breezes', 'S[OUTHWAR]d & W[ESTWAR]d; S.W.', 'S.S.W. tack; N[ORTHWAR]d', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT('type','right whales','action','saw & lowered','result','did not strike'), 'spoke Ship Japan. Dimon of F.H. 2 whales this season.', 0, 0),
    (@voyage_albion_id, '1856-07-30 00:00:00', 'Bristol Bay (Spoke Ships & Whaling Attempt)', 57.000, -163.000, 'whaling attempt; spoke ship', 'light winds; light breezes; strong breezes', 'S.W.; NN.E.; N[ORTHWAR]d & E[ASTWAR]d', 'S.S.W.', JSON_ARRAY(JSON_OBJECT('name','Levi Starbuck','home_port','New Bedford'), JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT('type','right whales','action','lowered & chased','result','did not strike'), 'spoke ship Levi Starbuck (4 whales this season, boiling).', 0, 0),
    (@voyage_albion_id, '1856-07-31 00:00:00', 'Bristol Bay (Lost Line)', 57.217, -163.000, 'whaling attempt; gear issue', 'strong breezes; rugged', 'E[ASTWAR]d; E to S.E.', 'N.W.', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT('type','right whale','action','lowered & struck & parted line','result','parted the line; Came on board again'), 'lowered again all 4 boats. struck a whale & parted the line.', 0, 0),
    (@voyage_albion_id, '1856-08-01 00:00:00', 'Bristol Bay (Shared Kill)', 57.100, -163.500, 'whaling — shared kill; injury', 'fine weather; moderate breezes; strong breezes', 'S.E to E; S.E to S.', 'S.W. tack', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT('type','right whale','action','lowered; Japan struck & our boats helped kill','result','struck & killed him on shares'), 'one of the Japan''s boats struck a whale. & our boats struck. & helped kill him on shares. Mr Howland. 4th mate got badly hurt by the whale.', 0, 1),
    (@voyage_albion_id, '1856-08-04 00:00:00', 'Bristol Bay (Successful Whaling)', 57.133, -163.500, 'whaling — took whale; cutting in', 'light breezes; thick weather', 'S.E to S.', 'S.W. tack', JSON_ARRAY(JSON_OBJECT('name','James Andrews (bark)','home_port','New Bedford')), JSON_OBJECT('type','right whale','action','lowered & struck & killed','barrels',120,'result','successful'), 'saw several right whales. lowered the boats. struck one. killed him. S.B ... 120.', 0, 0),
    (@voyage_albion_id, '1856-08-06 00:00:00', 'Bristol Bay (Lost Whale - Sunk)', 57.000, -163.000, 'whaling — lost whale; boiling', 'light airs; light breezes', 'S[OUTHWAR]d & E[ASTWAR]d; S[OUTHWAR]d', 'E[ASTWAR]d; S[OUTHWAR]d', JSON_ARRAY(JSON_OBJECT('name','bark','home_port',NULL)), JSON_OBJECT('type','right whale','action','lowered & struck & killed & sunk','barrels',80,'result','killed & sunk him'), 'saw right whales. lowered 2 boats. struck one. killed & sunk him. S.B ... 80.', 0, 0),
    (@voyage_albion_id, '1856-08-08 00:00:00', 'Bristol Bay (Found Sunken Whale)', 57.000, -163.000, 'finished stowing; cutting in sunken whale', 'light winds; strong breezes', 'S[OUTHWAR]d', 'Western tack', JSON_ARRAY(JSON_OBJECT('name','ships','home_port',NULL)), JSON_OBJECT('type','sunken whale','action','hove up anchor & cut in','result','got underway & commenced cutting in the whale'), 'finished stowing down oil 110 Bbls; got underway & commenced cutting in the whale.', 0, 0),
    (@voyage_albion_id, '1856-08-10 00:00:00', 'Bristol Bay (Boiling & Spoke Ships)', 56.917, -161.617, 'boiling; spoke ships', 'moderate winds; thick fog; strong breezes', 'S[OUTHWAR]d & W[ESTWAR]d; N[ORTHWAR]d & E[ASTWAR]d', 'Western tack; S.S.E.', JSON_ARRAY(JSON_OBJECT('name','Callao','home_port','New Bedford'), JSON_OBJECT('name','Mogul','home_port','New London')), JSON_OBJECT(), 'finished cutting; commenced boiling; spoke ship Callao; Mogul in company.', 0, 0),
    (@voyage_albion_id, '1856-08-12 00:00:00', 'Bristol Bay (Finished Boiling)', 56.633, -162.000, 'finished boiling', 'strong winds; thick weather', 'S.W.; S[OUTHWAR]d & W[ESTWAR]d', 'S.S.E. tack', JSON_ARRAY(), JSON_OBJECT('type','whale oil','action','finished boiling & cooled down','barrels',85,'result','finished boiling. & cooled down 85 Bbls'), 'cooled down 85 Bbls.', 0, 0),
    (@voyage_albion_id, '1856-08-20 00:00:00', 'Bristol Bay (Found Dead Whale)', 56.850, -161.800, 'cutting in dead whale; spoke ships; boiling', 'fine weather; brisk winds; strong winds', 'S[OUTHWAR]d; S.E.; E[ASTWAR]d', 'WS.W.', JSON_ARRAY(JSON_OBJECT('name','William Tell','home_port','Sag Harbor'), JSON_OBJECT('name','Salamandre (French Bark)','home_port','Harve')), JSON_OBJECT('type','dead whale','action','took alongside & cut in','barrels',35,'result','finished cutting & started the fires'), 'took alongside part of a dead whale...head & flukes gone; spoke ship William Tell (8 whales this season); spoke French Bark Salamandre (1 whale this season).', 0, 0),
    (@voyage_albion_id, '1856-08-21 00:00:00', 'Bristol Bay (Boiling & Death of Mate)', 57.000, -162.333, 'boiling; burial; spoke ship', 'strong breezes; thick & rainy; light airs', 'E[ASTWAR]d; S.W.', 'N[ORTHWAR]d', JSON_ARRAY(JSON_OBJECT('name','Salamandre (French Bark)','home_port','Harve')), JSON_OBJECT(), 'Died at 9 PM...Fortune H. Taylor. 4th mate. aged 27 years; boiling etc. buried the man.', 0, 1),
    (@voyage_albion_id, '1856-08-22 00:00:00', 'Bristol Bay (Finished Boiling & Spoke Ships)', 57.000, -162.500, 'finished boiling; spoke ships; whaling attempt', 'light wind; thick fog; thick weather & rain', 'N[ORTHWAR]d; E[ASTWAR]d', 'N.W. tack', JSON_ARRAY(JSON_OBJECT('name','Cleone (bark)','home_port','New Bedford'), JSON_OBJECT('name','Scotland','home_port','New Bedford'), JSON_OBJECT('name','James Andrews','home_port','New Bedford')), JSON_OBJECT('type','whale oil','action','cooled down','barrels',35,'result','cooled down 35 Bbls'), 'cooled down 35 Bbls (oil from Aug 20th dead whale); spoke Bark Cleone (7 whales this season); spoke ship Scotland (8 whales this season).', 0, 0),
    (@voyage_albion_id, '1856-08-24 00:00:00', 'Bristol Bay (Spoke Ship)', 56.767, -162.500, 'spoke ship; whaling sightings', 'light breezes; light airs', 'E[ASTWAR]d; N.W.', 'S.W. tack; N.E.', JSON_ARRAY(JSON_OBJECT('name','Good Return','home_port','New Bedford')), JSON_OBJECT('type','right whales','action','saw ship take a whale','result',NULL), 'saw a ship take a whale alongside; boarded ship Good Return (cutting; 5 whales this season).', 0, 0),
    (@voyage_albion_id, '1856-08-27 00:00:00', 'Bristol Bay (Found Dead Whale)', 56.000, -162.450, 'found dead whale; cutting in', 'rugged weather; strong winds', 'N.N.W.', 'W.S.W.', JSON_ARRAY(), JSON_OBJECT('type','dead whale','action','saw & took alongside & cut in','result','chopped off the flukes & let the rest go'), 'saw a dead whale...commenced cutting; got the throat & lips & almost half the body.', 0, 0),
    (@voyage_albion_id, '1856-08-28 00:00:00', 'Bristol Bay (Boiling Prep)', 56.000, -162.450, 'boiling prep; spoke ship', 'rugged weather; strong winds', 'N.W.', 'N.N.E.', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','boiling prep; saw','result','two irons in the whale. ship''s mark J.M.'), 'boiling etc; two irons in the whale. ship''s mark J.M. probably James Maury of New Bedford.', 0, 0),
    (@voyage_albion_id, '1856-09-04 00:00:00', 'Bristol Bay (Successful Whaling)', 57.283, -161.383, 'whaling — took whale; cutting in', 'moderate breezes; light breezes; brisk winds', 'N.E to N.W.; S.W.', 'S.S.E. tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','lowered & struck & killed','barrels',140,'result','successful'), 'saw right whales lowered 3 boats struck & killed one. L.B ... 140.', 0, 0),
    (@voyage_albion_id, '1856-09-05 00:00:00', 'Bristol Bay (Successful Whaling)', 57.000, -161.000, 'whaling — took whale; cutting prep', 'moderate breezes; blowing a gale', 'S.W.; E[ASTWAR]d', 'S.S.E. tack', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw & lowered & struck & killed','barrels',140,'result','successful'), 'saw another right whale. lowered 2 boats. struck & killed him. L.B ... 140.', 0, 0),
    (@voyage_albion_id, '1856-09-09 00:00:00', 'Bristol Bay (Boiling & Gale)', 57.667, -163.467, 'boiling; stowing oil; gale', 'blowing a strong gale; strong winds', 'E[ASTWAR]d; S[OUTHWAR]d & E[ASTWAR]d', 'WS.W.; S[OUTHWAR]d', JSON_ARRAY(), JSON_OBJECT(), 'boiling & stowing down oil. Fore Hold; set double reefed Main Topsail & broke out the After Hold for stowing down.', 0, 0),
    (@voyage_albion_id, '1856-09-13 00:00:00', 'Bristol Bay (Finished Boiling & Whaling Attempt)', 57.133, -153.233, 'finished boiling; whaling attempt; scouting', 'fine weather; moderate breezes', 'N..W.; W[ESTWAR]d', 'S.W. tack', JSON_ARRAY(), JSON_OBJECT('type','right whales','action','lowered & chased','result','got nothing'), 'finished boiling & cooled down. stowed off the After Hold; saw several whales lowered 3 boats.', 0, 0),
    (@voyage_albion_id, '1856-09-14 00:00:00', 'Bristol Bay (Whaling Attempt & Spoke Ship)', 56.717, -162.000, 'whaling attempt; spoke ship', 'fine weather; light breezes', 'W[ESTWAR]d', 'S.W. tack', JSON_ARRAY(JSON_OBJECT('name','William Thompson','home_port','New Bedford')), JSON_OBJECT('type','right whale','action','lowered & struck & drew the irons','result','drew the irons'), 'lowered 2 boats for right whales struck one & drew the irons; spoke Ship William Thompson (900 this season).', 0, 0),
    (@voyage_albion_id, '1856-09-15 00:00:00', 'Bristol Bay (Spoke Ship)', 56.833, -162.800, 'spoke ship; routine sailing', 'fine weather; light breezes; light airs & calms', 'W[ESTWAR]d; N[ORTHWAR]d & W[ESTWAR]d', 'N.W.', JSON_ARRAY(JSON_OBJECT('name','Charles Carroll','home_port','New London')), JSON_OBJECT(), 'spoke Ship Charles Carroll (1800 this season); 10 ships in sight.', 0, 0),
    (@voyage_albion_id, '1856-09-16 00:00:00', 'Bristol Bay (Spoke Ship & Whaling Attempt)', 57.000, -163.000, 'spoke ship; whaling attempt', 'fine weather; light breezes', 'N[ORTHWAR]d; N[ORTHWAR]d & W[ESTWAR]d', 'S.W.; N.E. tack', JSON_ARRAY(JSON_OBJECT('name','Braganza','home_port','New Bedford')), JSON_OBJECT('type','right whale','action','lowered','result','could not strike'), 'spoke Ship Braganza (6 whales this season).', 0, 0),
    (@voyage_albion_id, '1856-09-18 00:00:00', 'Bristol Bay (Spoke Ships & Found Carcass)', 57.167, -164.000, 'spoke ships; found carcass; whaling attempt', 'fine weather; light breezes', 'N.W.; N[ORTHWAR]d', 'Western tack', JSON_ARRAY(JSON_OBJECT('name','William Tell','home_port','Sag Harbor'), JSON_OBJECT('name','William Thompson','home_port','New Bedford')), JSON_OBJECT('type','stinker / carcass','action','lowered a boat','result','found _ a carcass'), 'spoke Ship William Tell (10 whales this season); spoke Wm Thompson (6 whales); lowered a boat for a stinker and found _ a carcass.', 0, 0),
    (@voyage_albion_id, '1856-09-21 00:00:00', 'Bristol Bay (Successful Whaling)', 57.400, -164.850, 'whaling — took whale; cutting prep', 'clear weather; moderate winds', 'NN.W.; N[ORTHWAR]d & W[ESTWAR]d', 'N[ORTHWAR]d & E[ASTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Liverpool','home_port','New Bedford')), JSON_OBJECT('type','right whale','action','saw & lowered & struck & killed','barrels',120,'result','successful'), 'saw right whales lowered 3 boats, struck a whale & killed him. S.B ... 120.', 0, 0),
    (@voyage_albion_id, '1856-09-23 00:00:00', 'Bristol Bay (Spoke Ship & Boiling)', 57.333, -165.283, 'boiling; spoke ship; stowing prep', 'fine weather; moderate breezes', 'N[ORTHWAR]d & W[ESTWAR]d; N[ORTHWAR]d', 'Western tack', JSON_ARRAY(JSON_OBJECT('name','Alice Frazier (bark)','home_port','New Bedford')), JSON_OBJECT('type','carcass','action','saw','result',NULL), 'boiling etc; spoke Bark Alice Frazier (3 whales the season); broke out the Fore Hold for stowing down.', 0, 0);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1856-09-24 00:00:00', 'Bering Sea (Boiling & Found Stinker)', 57.600, -166.067, 'boiling; found dead whale; cutting in', 'fine weather; light breezes', 'N[ORTHWAR]d', 'Western tack', JSON_ARRAY(), JSON_OBJECT('type','stinker','action','saw & got alongside & cut in','barrels',75,'result','finished boiling & cooled down 75 Bbls'), 'finished boiling & cooled down 75 Bbls (likely the 120 bbl kill); saw a stinker...got him alongside...cutting the whale.', 0, 0),
    (@voyage_albion_id, '1856-09-25 00:00:00', 'Bering Sea (Cutting & Death of Crewman)', 57.667, -166.250, 'cutting in; boiling prep; death of crewman', 'fine weather; light breezes', 'N[ORTHWAR]d', '', JSON_ARRAY(), JSON_OBJECT('type','whales (right)','action','saw & lowered','result','did not strike'), 'finished cutting; Died this morning at 5 A.M. Harry Coffin. native of the Sandwich Islands.', 0, 1),
    (@voyage_albion_id, '1856-09-28 00:00:00', 'Off St. George Island (Pribilofs)', 56.067, -170.017, 'sighted land; departed south', 'strong gales; strong winds', 'N[ORTHWAR]d', 'S.W by S.; S. by W.', JSON_ARRAY(), JSON_OBJECT(), 'saw the island of St. George; sent down the cutting gear & took in the Waist Boat.', 0, 0),
    (@voyage_albion_id, '1856-09-30 00:00:00', 'Aleutians (Passage)', 52.417, -171.800, 'passed through islands; gear work', 'moderate all sail breeze; fine weather', 'N[ORTHWAR]d', 'S by E 1/2 E', JSON_ARRAY(), JSON_OBJECT(), '4 islands in sight, Amoukhta, Tchagoula, & Younaska...Seguam; sent up the new Fore Topmast.', 0, 0),
    (@voyage_albion_id, '1856-10-10 00:00:00', 'North Pacific Ocean (Blackfish Sighting)', 38.267, -160.283, 'whaling attempt', 'light airs; brisk winds', 'N[ORTHWAR]d; S.W & W[ESTWAR]d', 'S.E by S.', JSON_ARRAY(), JSON_OBJECT('type','Blackfish','action','saw & lowered','result','did not strike'), 'saw Blackfish. lowered one boat.', 0, 0),
    (@voyage_albion_id, '1856-10-18 00:00:00', 'Off Maui/Molokai (Sighted Land & Spoke Ship)', 21.833, -156.017, 'spoke ship; sighted land; beating up', 'variable winds; light airs & baffling', 'S to S.E.', 'S.S.E.', JSON_ARRAY(JSON_OBJECT('name','Lark (bark)','home_port','New London')), JSON_OBJECT(), 'spoke Bark Lark (1700 the season); saw the land, Maui & Molokoi.', 0, 0),
    (@voyage_albion_id, '1856-10-20 00:00:00', 'Lahaina, Maui (Anchorage)', 20.878, -156.685, 'anchored; provisioning prep', 'fine weather; light & variable winds', '', '', JSON_ARRAY(), JSON_OBJECT(), 'came to anchor in Lahaina in 11 fathoms; washed ship outside.', 0, 0),
    (@voyage_albion_id, '1856-10-21 00:00:00', 'Lahaina, Maui (Cargo Transfer)', 20.878, -156.685, 'cargo transfer', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Crystal Palace','home_port',NULL)), JSON_OBJECT(), 'shipped all the bone on board Ship Crystal Palace. 127 Bundles weighing 11..489 lbs.', 0, 0),
    (@voyage_albion_id, '1856-10-22 00:00:00', 'Lahaina, Maui (Received Oil)', 20.878, -156.685, 'received oil cargo', '', '', '', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT('type','oil (sperm/whale)','action','received oil','barrels',11,'result','11 casks of oil from Ship Japan'), 'took on board 11 casks of oil from Ship Japan. stowed the oil between decks.', 0, 0),
    (@voyage_albion_id, '1856-11-03 00:00:00', 'Lahaina, Maui (Departure Prep)', 20.878, -156.685, 'departure prep; anchored again', 'light winds', 'S[OUTHWAR]d; W[ESTWAR]d', 'lay off & on', JSON_ARRAY(), JSON_OBJECT(), 'hove up the anchor & got under weigh...anchor came up foul...came to with the starboard anchor.', 0, 0),
    (@voyage_albion_id, '1856-11-05 00:00:00', 'Lahaina, Maui (Departure)', 20.878, -156.685, 'departed', 'light & baffling winds', '', 'W[ESTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven'), JSON_OBJECT('name','Levi Starbuck','home_port','New Bedford')), JSON_OBJECT(), 'took the anchor...in company with ships Japan & Levi Starbuck.', 0, 0),
    (@voyage_albion_id, '1856-11-06 00:00:00', 'Off Honolulu, Oahu', 21.300, -157.850, 'captain ashore', 'light trades', 'E[ASTWAR]d', 'W[ESTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven'), JSON_OBJECT('name','Levi Starbuck','home_port','New Bedford')), JSON_OBJECT(), 'off Diamond Head; Capt[AIN] & boats crew went on shore at Honolulu.', 0, 0),
    (@voyage_albion_id, '1856-11-09 00:00:00', 'Off Oahu (Departure Southbound)', 21.300, -157.850, 'captain returned; departed', 'light trades', 'E[ASTWAR]d', 'S by E to S.S.W.', JSON_ARRAY(JSON_OBJECT('name','Baltic (bark)','home_port','New Bedford')), JSON_OBJECT(), 'Capt[AIN] came on board. made sail on the Southern tack.', 0, 0),
    (@voyage_albion_id, '1856-11-16 00:00:00', 'Pacific Ocean (Whaling Sighting)', 5.783, -153.100, 'whaling sighting; routine sailing', 'brisk trades; moderate breezes', 'S.E.; E[ASTWAR]d', 'EN.E.; SSW.', JSON_ARRAY(), JSON_OBJECT('type','sperm whale','action','saw spouts','result','lost the run of him'), 'saw spouts. probably a sperm whale but lost the run of him.', 0, 0),
    (@voyage_albion_id, '1856-11-19 00:00:00', 'Near the Line', -2.000, -157.400, 'routine sailing; gear work', 'brisk trades', 'ESE.', 'S & S by W.', JSON_ARRAY(), JSON_OBJECT(), 'making topgall''t mast & working on the rigging.', 0, 0),
    (@voyage_albion_id, '1856-11-28 00:00:00', 'South Pacific Ocean (Received Oil)', -16.433, -157.150, 'stowing oil; routine sailing', 'moderate breezes; brisk winds; squally', 'NN.E.; E to S.E.', 'SSE.', JSON_ARRAY(JSON_OBJECT('name','Japan','home_port','Fairhaven')), JSON_OBJECT(), 'employed stowing down oil in the After Hold. (rec[EIVE]d from Japan ~ 48 bbls).', 0, 0),
    (@voyage_albion_id, '1856-11-30 00:00:00', 'Near Hervey''s Island/Aitutaki (Spoke Ship)', -18.917, -158.850, 'sighted land; spoke ship', 'light breezes; brisk all sail breeze', 'E[ASTWAR]d; N.E.', 'W.S.W.; W.N.W.', JSON_ARRAY(JSON_OBJECT('name','Baltic (bark)','home_port','New Bedford')), JSON_OBJECT(), 'saw Hervey''s Island; spoke Bark Baltic (40 spm since leaving the Sandwich Islands).', 0, 0),
    (@voyage_albion_id, '1856-12-02 00:00:00', 'Rarotonga, Cook Islands (Trading)', -21.200, -159.770, 'trading; laying off & on', 'fine weather; light breezes; strong winds & squally', 'E[ASTWAR]d; S to SE.', 'E[ASTWAR]d', JSON_ARRAY(JSON_OBJECT('name','Baltic (bark)','home_port','New Bedford')), JSON_OBJECT('type','sperm whale (?)','action','saw','result','lost the run of him in the rain squalls'), 'sent 2 boats ashore. lay off & on got off 3 boatloads of wood.', 0, 0),
    (@voyage_albion_id, '1856-12-08 00:00:00', 'Rarotonga, Cook Islands (Departure Prep)', -21.200, -159.770, 'departed prep; provisioning', 'light airs & baffling; calms; light breezes', 'S[OUTHWAR]d & E[ASTWAR]d', 'S.W. tack', JSON_ARRAY(), JSON_OBJECT(), 'brought off 2 loads of wood etc. Capt[AIN]. came aboard.', 0, 0),
    (@voyage_albion_id, '1856-12-10 00:00:00', 'South Pacific Ocean', -25.833, -163.333, 'whaling sighting; routine sailing', 'cloudy weather; strong winds', 'S.E.; E & ENE.', 'S.S.W.; S.W by S.', JSON_ARRAY(), JSON_OBJECT('type','whale','action','saw single breach','result',NULL), 'saw single breach.', 0, 0),
    (@voyage_albion_id, '1856-12-15 00:00:00', 'South Pacific Ocean', -29.000, -170.367, 'spoke ship (refused)', 'rugged weather; strong winds', 'E[ASTWAR]d', 'W by S.; W.S.W.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT(), 'passed a ship on the Southern tack. but he would not speak us.', 0, 0),
    (@voyage_albion_id, '1856-12-19 00:00:00', 'Near Sunday Island/Kermadec Islands', -30.500, -178.633, 'sighted land; gear work', 'moderate breezes; fine weather', 'E.', 'W by S.; S.W.', JSON_ARRAY(), JSON_OBJECT(), 'saw Recherche or Sunday Island; saw Macauley''s Island; saw Curtis''s Rocks.', 0, 0),
    (@voyage_albion_id, '1856-12-23 00:00:00', 'Pacific Ocean', -32.783, -178.467, 'whaling attempt; gear work', 'cloudy weather; light airs; fine weather', 'N[ORTHWAR]d; W.', 'Northern tack', JSON_ARRAY(), JSON_OBJECT('type','blackfish; sunfish','action','saw & lowered','result','did not strike'), 'saw blackfish, lowered 2 boats; saw sunfish, lowered a boat.', 0, 0),
    (@voyage_albion_id, '1856-12-25 00:00:00', 'Cruising near French Rock/Kermadecs (Christmas)', -32.517, -178.867, 'whaling attempt', 'fine weather; light airs & calms', 'S[OUTWAR]d', 'N.W by W.', JSON_ARRAY(), JSON_OBJECT('type','blackfish; Killers','action','lowered 3 boats','result','proved to be Killers'), 'Christmas Day; lowered 3 boats for blackfish & they proved to be Killers.', 0, 0),
    (@voyage_albion_id, '1856-12-26 00:00:00', 'Cruising near French Rock (Spoke Ship)', -32.833, -179.917, 'spoke ship; routine sailing', 'light airs; strong breezes & rugged', 'S[OUTHWAR]d; S.E to E.', 'N.W by W.', JSON_ARRAY(JSON_OBJECT('name','Narragansett','home_port','Nantucket')), JSON_OBJECT(), 'spoke Ship Narragansett (14 mo[NTH]s 120 spm).', 0, 0),
    (@voyage_albion_id, '1856-12-30 00:00:00', 'Cruising near French Rock (Whaling Attempt)', -31.750, 179.500, 'whaling attempt', 'fine weather; light winds', 'E[ASTWAR]d; S[OUTHWAR]d', 'S.W by S.; N[ORTHWAR]d', JSON_ARRAY(), JSON_OBJECT('type','large sperm whales (3)','action','saw & lowered & chased','result','did not strike'), 'saw 3 large sperm whales. lowered 3 boats.', 0, 0),
    (@voyage_albion_id, '1857-01-02 00:00:00', 'Cruising near French Rock (Whaling Attempt)', -31.667, 179.400, 'whaling attempt', 'fine weather; light breezes; squally', 'S.E to E.', 'S.S.W.', JSON_ARRAY(), JSON_OBJECT('type','sperm whales','action','saw & lowered & chased','result','could not catch them'), 'saw sperm whales going quick lowered 3 boats.', 0, 0),
    (@voyage_albion_id, '1857-01-06 00:00:00', 'Pacific Ocean', -37.500, 179.900, 'whaling attempt; gear work', 'fine weather; strong breezes & rugged', 'W.S.W.; S.W.', 'SS.E.', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','saw & lowered & shot & killed','result','got nothing'), 'saw blackfish, lowered 3 boats in chase. shot & killed one with a bale. got nothing.', 0, 0),
    (@voyage_albion_id, '1857-01-09 00:00:00', 'Pacific Ocean (Heavy Weather)', -41.300, -178.667, 'gale; gear work', 'all sail breeze; increasing to a gale', 'N[ORTHWAR]d; N.W to W.', 'S by W.', JSON_ARRAY(), JSON_OBJECT(), 'unbent the Mizzen Topsail; steering S by W.', 0, 0),
    (@voyage_albion_id, '1857-01-14 00:00:00', 'Pigeon Harbor, New Zealand (Anchorage)', -43.600, 172.900, 'anchored; provisioning', 'brisk winds; thick & rainy', 'SE to E.', 'Pigeon Harbor', JSON_ARRAY(), JSON_OBJECT(), 'came to anchor in Pigeon Harbor...Bank''s Peninsula; Sent a raft of casks ashore for water.', 0, 0),
    (@voyage_albion_id, '1857-01-22 00:00:00', 'Pigeon Harbor, New Zealand (Departure)', -43.600, 172.900, 'departed; whaling — took blackfish', 'moderate breezes; brisk winds; light airs & calms', 'S[OUTHWAR]d; S.S.E.', 'Eastern tack', JSON_ARRAY(), JSON_OBJECT('type','blackfish (4)','action','saw & lowered & took','result','took 4 & got them to the ship & hove them in'), 'hove up the anchor...went to sea; saw blackfish. lowered all 4 boats and took 4.', 0, 0),
    (@voyage_albion_id, '1857-01-23 00:00:00', 'Off Bank''s Peninsula (Boiling)', -44.933, 174.117, 'boiling blackfish', 'light airs & calms; light breezes', 'E. to ES.E.; SES.', 'S[OUTHWAR]d', JSON_ARRAY(), JSON_OBJECT(), 'employed boiling blackfish.', 0, 0),
    (@voyage_albion_id, '1857-01-28 00:00:00', 'South Pacific Ocean (Homeward Leg)', -51.950, -169.633, 'routine sailing; gear work', 'thick & rainy weather; clear weather; strong breezes', 'WN.W.; W to WS.W.', 'E by S.; E & E by S.', JSON_ARRAY(), JSON_OBJECT(), 'bent a jib for a middle staysail; bent & set lower stud''gsail.', 0, 0),
    (@voyage_albion_id, '1857-02-04 00:00:00', 'South Pacific Ocean (Heavy Leak)', -56.000, -133.500, 'heavy weather; gear issue', 'strong breezes; strong gales; thick & heavy rain', 'N.W.; NN.E.', 'E.', JSON_ARRAY(), JSON_OBJECT(), 'Ship leaks at the rate of 6000 strokes in 24 hours.', 0, 0),
    (@voyage_albion_id, '1857-02-15 00:00:00', 'Near Cape Horn (Spoke Ship)', -57.733, -70.717, 'gale; spoke ship', 'strong gales & squalls', 'W.S.W.', 'N.E by E.; EN.E.', JSON_ARRAY(JSON_OBJECT('name','Arab (bark)','home_port','Fair Haven')), JSON_OBJECT(), 'spoke Bark Arab homeward bound lying to.', 0, 0),
    (@voyage_albion_id, '1857-02-16 00:00:00', 'E. of Cape Horn (Gear Damage)', -57.500, -66.067, 'gale; gear damage', 'strong gales; heavy squalls', 'N.W & WN.W.', 'N.E by E.', JSON_ARRAY(JSON_OBJECT('name','ship','home_port',NULL)), JSON_OBJECT(), 'carried away the jib martingale & lost the chain; Saw one outward bound ship.', 0, 0),
    (@voyage_albion_id, '1857-02-18 00:00:00', 'E. of Cape Horn (Gear Damage & Repair)', -55.000, -58.667, 'gear damage; repair', 'brisk winds; blowing on a gale', 'N to NN.W.; WN.W.', 'N. by E.; N.E by N.', JSON_ARRAY(), JSON_OBJECT(), 'discovered the Foretopmast to be carried away at the sheavehole; sent down Fore Top gallant yard & mast.', 0, 0),
    (@voyage_albion_id, '1857-03-02 00:00:00', 'Off Rio de la Plata (Spoke Ship)', -34.750, -46.267, 'spoke ship; routine sailing', 'light breezes; light airs', 'N.W to W.; S.W.', 'N.E by N.', JSON_ARRAY(JSON_OBJECT('name','Parga (English bark)','home_port','Swansea')), JSON_OBJECT(), 'spoke English bark Parga...bound to Valparaiso.', 0, 0),
    (@voyage_albion_id, '1857-03-13 00:00:00', 'South Atlantic Ocean (Spoke Ship)', -32.283, -33.533, 'spoke ship; routine sailing', 'fine weather; light airs', 'N.E to E.', 'N by W to N by E.', JSON_ARRAY(JSON_OBJECT('name','Dutch bark','home_port',NULL)), JSON_OBJECT(), 'lowered a boat & boarded Dutch bark...bound to Batavia.', 0, 0),
    (@voyage_albion_id, '1857-03-20 00:00:00', 'South Atlantic Ocean (Spoke Ship)', -22.300, -30.517, 'spoke ship; routine sailing', 'light breezes; moderate breezes', 'S to S.E.; E[ASTWAR]d', 'N by E.', JSON_ARRAY(JSON_OBJECT('name','Harriot Erving','home_port',NULL)), JSON_OBJECT(), 'spoke ship "Harriot Erving." 46 days from Talcahuano for Boston.', 0, 0),
    (@voyage_albion_id, '1857-03-29 00:00:00', 'South Atlantic Ocean (Spoke Ship)', -9.017, -34.700, 'spoke ship; routine sailing', 'fine weather; fresh breeze', 'E[ASTWAR]d', 'N by E.; N.', JSON_ARRAY(JSON_OBJECT('name','Omega','home_port','Nantucket')), JSON_OBJECT(), 'spoke ship Omega (2100 wh[ALE] bound home); steered N in company.', 0, 0);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1857-03-30 00:00:00', 'Off Cape St. Augustine (Sighted Land)', -6.833, -35.267, 'sighted land; spoke ship; routine sailing', 'fine weather; moderate breezes', 'E[ASTWAR]d', 'N; NW by W', JSON_ARRAY(JSON_OBJECT('name','Omega','home_port','Nantucket')), JSON_OBJECT(), 'the land in sight dist[ANT] 10 miles; Omega in company.', 0, 0),
    (@voyage_albion_id, '1857-03-31 00:00:00', 'South Atlantic Ocean', -4.700, -35.350, 'routine sailing; provisioning prep', 'fine weather; moderate breeze; light breezes', 'E[ASTWAR]d; SE', 'N', JSON_ARRAY(JSON_OBJECT('name','Omega','home_port','Nantucket')), JSON_OBJECT(), 'breaking out between decks. restowing etc.', 0, 0),
    (@voyage_albion_id, '1857-04-03 00:00:00', 'Crossed the Line (Northward)', 0.000, -40.550, 'crossed the line; routine sailing', 'fine weather; moderate breeze', 'N.E.', 'NN.W; NW by N', JSON_ARRAY(), JSON_OBJECT(), 'Crossed the Line (North Atlantic).', 0, 0),
    (@voyage_albion_id, '1857-04-06 00:00:00', 'North Atlantic Ocean (Trades)', 6.633, -46.433, 'routine sailing', 'strong trades; brisk winds', 'N.E.; EN.E.', 'N.W by N; N.W 1/2 N', JSON_ARRAY(), JSON_OBJECT(), 'set the starboard studdingsails.', 0, 0),
    (@voyage_albion_id, '1857-04-14 00:00:00', 'North Atlantic Ocean', 20.033, -55.850, 'routine sailing; gulfweed sighted', 'fine weather; light breeze', 'S.E & ES.E.', 'N.W; N.W 1/2 N', JSON_ARRAY(), JSON_OBJECT(), 'saw plenty of gulfweed.', 0, 0),
    (@voyage_albion_id, '1857-04-19 00:00:00', 'North Atlantic Ocean (Spoke Ship)', 24.200, -59.883, 'spoke ship; routine sailing', 'fine weather; moderate breeze', 'NN.W.; W[ESTWAR]d', 'Western tack; NN.W.', JSON_ARRAY(JSON_OBJECT('name','Metacom','home_port','New Bedford')), JSON_OBJECT(), 'spoke ship Metacom (2700 wh[ALE]); Metacom in company.', 0, 0),
    (@voyage_albion_id, '1857-04-30 00:00:00', 'Off Bermuda/New England Approach (Gear Disposal)', 35.133, -70.417, 'gale; gear disposal; passed ships', 'light airs; heavy squalls; strong breeze', 'S[OUTHWAR]d; N.E.', 'N.W & NW by N.', JSON_ARRAY(JSON_OBJECT('name','ships','home_port',NULL)), JSON_OBJECT(), 'broke up the tryworks & threw them overboard; passed 4 outward bound ships.', 0, 0),
    (@voyage_albion_id, '1857-05-03 00:00:00', 'Cuttyhunk/New Bedford Approach (Arrival)', 41.350, -70.933, 'sighted land; took pilot; anchored', 'strong winds; thick & rain', 'S.S.E.; S.W.', 'N; EN.E; E by N.', JSON_ARRAY(), JSON_OBJECT(), 'saw Long Island ahead...Block Island; got a pilot from Cuttyhunk; came to anchor in 12 fathoms.', 0, 0),
    (@voyage_albion_id, '1857-05-04 00:00:00', 'New Bedford / Round Hill (Final Anchorage)', 41.637, -70.920, 'final anchorage; voyaging end', 'light airs & foggy', 'S.W.', '', JSON_ARRAY(), JSON_OBJECT(), 'came to again off Cl[???] Point light; Absent 29 months & 26 days.', 0, 0);


INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_albion_id, '1857-05-04 00:00:00', 'Fairhaven/New Bedford (Voyage End Summary)', 41.637, -70.917, 'voyage end: oil summary', '', '', '', JSON_ARRAY(), JSON_OBJECT('turned out',1354,'sent home',545,'sperm_oil',75,'result','Total 1974 bbls'), 'Voyage Absent 29 months & 26 days. Turned out 1354 wh[ale]; sent home 545 wh[ale]; 75 spm. Total 1974 Bbls.', 0, 3);

