-- ───────────────────────────────────────────────────────────────
-- Seed: Ship (Indian Chief)
-- ───────────────────────────────────────────────────────────────
INSERT INTO ships (ship_name, home_port)
VALUES ('Indian Chief', 'New London')
ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id);

-- Capture ship id
SET @ship_id := LAST_INSERT_ID();

-- ───────────────────────────────────────────────────────────────
-- Seed: Voyages (Indian Chief, J. F Skinner)
-- ───────────────────────────────────────────────────────────────
INSERT INTO voyages (
    ship_id,
    starting_port,
    destination_port,
    captain_name,
    crew_count,
    casualties,
    start_date
) VALUES (
             @ship_id,
             'New Bedford',
             'Sea of Okhotsk via New Zealand & Guam',
             'Nathaniel Lorins Cannon',
             0,
             0,
             '1842-12-21 00:00:00'
         );

-- Capture voyage id
SET @voyage_id := LAST_INSERT_ID();

-- ───────────────────────────────────────────────────────────────
-- Seed: Events (Indian Chief, October 1842 - April 1843)
-- ───────────────────────────────────────────────────────────────
INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_id, '1842-10-01 00:00:00', 'New London (near port)', 41.350, -72.098, 'hove short and got underway; stowing anchors', 'light breezes', 'SSW', 'clearing up for sea', JSON_ARRAY(), JSON_OBJECT(), 'Light airs and baffling.', 0, 0),
    (@voyage_id, '1842-10-02 00:00:00', 'Atlantic Ocean (off Montauk)', 40.450, -70.117, 'discharged pilot; routine sailing', 'light winds; pleasant weather', 'SSW', '', JSON_ARRAY(JSON_OBJECT('name','Candace','home_port','New London')), JSON_OBJECT(), 'Montauk light bearing W by S, 6 miles, then 15 miles at dark.', 0, 0),
    (@voyage_id, '1842-10-03 00:00:00', 'Atlantic Ocean (en route)', 38.900, -69.950, 'routine sailing', 'fresh breezes', 'SSW', 'SE by S', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1842-10-04 00:00:00', 'Atlantic Ocean (en route)', 37.400, -65.983, 'breaking out between decks and fitting the board', 'fine breezes', 'NW', '', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1842-10-05 00:00:00', 'Atlantic Ocean (en route)', 36.750, -61.933, 'ships duty', 'fine breezes', 'NW', '', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Two sail in sight.', 0, 0),
    (@voyage_id, '1842-10-07 00:00:00', 'Atlantic Ocean (en route)', 34.017, -55.767, 'routine sailing', 'fresh gales', 'NNW', 'SE by E', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'One sail in sight.', 0, 0),
    (@voyage_id, '1842-10-08 00:00:00', 'Atlantic Ocean (en route)', 32.167, -53.400, 'routine sailing', 'strong gales', 'NNW', 'SE by E', JSON_ARRAY(), JSON_OBJECT(), 'Under single reeft topsails.', 0, 0),
    (@voyage_id, '1842-10-09 00:00:00', 'Atlantic Ocean (en route)', 30.467, -51.167, 'employed in rigging', 'moderate breezes', 'NNE', 'SE by E', JSON_ARRAY(), JSON_OBJECT(), 'Under all sail.', 0, 0),
    (@voyage_id, '1842-10-17 00:00:00', 'Atlantic Ocean (en route)', 20.760, -47.083, 'employed variously in rigging', 'light breezes', 'ENE', 'SE', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1842-10-22 00:00:00', 'Atlantic Ocean (en route)', 18.033, -42.600, 'employed ratling rigging', 'calms, then light breeze', 'NE', 'SE by E', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Two sail in sight.', 0, 0),
    (@voyage_id, '1842-10-23 00:00:00', 'Atlantic Ocean (en route)', 17.400, -40.917, 'routine sailing', 'fresh breezes; squally later', 'NE, then ENE', 'ESE', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'One sail in sight.', 0, 0),
    (@voyage_id, '1842-10-24 00:00:00', 'Atlantic Ocean (en route)', 16.917, -40.517, 'saw finback', 'fresh breezes; heavy rain squalls', 'E, then SE', '', JSON_ARRAY(JSON_OBJECT('name','several','home_port',NULL)), JSON_OBJECT('type','finback','action','sightings','result',NULL), 'Several sail in sight.', 0, 0),
    (@voyage_id, '1842-10-25 00:00:00', 'Atlantic Ocean (en route)', 16.667, -40.217, 'routine sailing', 'strong breezes; fresh gales later; heavy rain squalls', 'SE', '', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Double reeft topsails; "Green hands aloft reefing topsails and such. A getting up stairs I never did see."', 0, 0),
    (@voyage_id, '1842-11-06 00:00:00', 'Atlantic Ocean (en route)', 8.467, -33.567, 'saw finback', 'light breezes; calm with rain squalls later', 'E', '', JSON_ARRAY(), JSON_OBJECT('type','finback','action','sightings','result',NULL), '', 0, 0),
    (@voyage_id, '1842-11-07 00:00:00', 'Atlantic Ocean (en route)', 7.800, -33.200, 'whaling attempt', 'light breezes; heavy rain squalls later', 'E', '', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','lowered and struck and drawed','result','no success/lost'), 'No barrel count mentioned; "struck and drawed" suggests loss.', 0, 0),
    (@voyage_id, '1842-11-17 00:00:00', 'Atlantic Ocean (en route)', 4.450, -27.767, 'steward punishment / crew change', 'light winds; heavy rain squalls', 'S, then SSE', 'All sail out', JSON_ARRAY(), JSON_OBJECT(), 'Isaac Foster steward used insulting language; flogged, put in irons; got loose, re-secured. Steward role changes twice.', 1, 0),
    (@voyage_id, '1842-11-19 00:00:00', 'Atlantic Ocean (en route)', 4.967, -27.083, 'whaling attempt', 'light variable winds', '', '', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','lowered two boats','result','no success'), 'Steward in irons.', 0, 0),
    (@voyage_id, '1842-11-28 00:00:00', 'Atlantic Ocean (en route)', 1.417, -26.917, 'steward returned to duty; routine sailing', 'light breezes', 'SSE', 'SW', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Steward returned to cook on promise to behave. Former cook remains steward. One sail in sight.', 0, 0),
    (@voyage_id, '1842-11-29 00:00:00', 'Atlantic Ocean (en route)', -0.417, -27.983, 'employed breaking out between decks and coopering the bread', 'fine breezes', 'SE', 'SSW', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Two sail in sight. Latt 25 miles S (likely a misreading/miscalculation for -0.417 S).', 0, 0),
    (@voyage_id, '1842-11-30 00:00:00', 'Atlantic Ocean (en route)', -0.833, -27.617, 'routine sailing', 'fine breezes', 'SE', 'SSW', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Two sail in sight.', 0, 0),
    (@voyage_id, '1842-12-05 00:00:00', 'Atlantic Ocean (en route)', -11.517, -28.817, 'employed repairing sails; building roundhouse', 'strong breezes', 'ESE', 'S', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','lost topmast ship','home_port',NULL)), JSON_OBJECT(), 'Two sail in sight. One ship lost her topmast in a squall.', 0, 0),
    (@voyage_id, '1842-12-16 00:00:00', 'Atlantic Ocean (en route)', -34.400, -14.183, 'spoke ship; routine sailing', 'strong breezes; hard gales later', 'N, then N', 'SE by S', JSON_ARRAY(JSON_OBJECT('name','English brig','home_port','England')), JSON_OBJECT(), 'Took in topgalant sails and double reeft the topsails.', 0, 0),
    (@voyage_id, '1842-12-17 00:00:00', 'Atlantic Ocean (en route)', -36.400, -12.333, 'saw finbacks; employed bending coarses and rigging', 'strong gales with rain; moderate later', 'NNW, then W, then WSW', 'SE by S', JSON_ARRAY(), JSON_OBJECT('type','finbacks','action','sightings','result',NULL), 'Under all sail.', 0, 0),
    (@voyage_id, '1842-12-18 00:00:00', 'Tristan da Cunha', -37.050, -12.350, 'made land; sent in two boats', 'light breezes; light airs and calms later', 'S', '', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Island made at 6:30 PM. Two sail seen.', 0, 0),
    (@voyage_id, '1842-12-19 00:00:00', 'Tristan da Cunha', -37.060, -12.330, 'whaling attempt; provisioning', 'light breezes; light winds and calms later', 'SW', 'in for the land', JSON_ARRAY(JSON_OBJECT('name','Phenix','home_port','New London')), JSON_OBJECT('type','right whale / sperm','action','saw/lowered','result','no success'), 'Captain and 2nd mate on shore. Three boats on shore getting off potatoes. Spoke Phenix (700 bbls oil).', 0, 0),
    (@voyage_id, '1842-12-20 00:00:00', 'Tristan da Cunha (departing)', -37.070, -12.300, 'getting recruits; spoke ships; departed', 'fine breezes', 'S, then W', 'E in company with Phenix', JSON_ARRAY(JSON_OBJECT('name','Bingham','home_port','Mystic'), JSON_OBJECT('name','Phenix','home_port','New London')), JSON_OBJECT(), 'Captain, mate, 3rd mate on shore. Boats came off with recruits and Governor Glass son Albert. Bingham with two whale.', 0, 0),
    (@voyage_id, '1842-12-21 00:00:00', 'Atlantic Ocean (en route)', -37.067, -9.100, 'routine sailing', 'fresh breezes', 'W', 'SE by E', JSON_ARRAY(JSON_OBJECT('name','Phenix','home_port','New London')), JSON_OBJECT(), 'Ship Phenix in company.', 0, 0),
    (@voyage_id, '1842-12-24 00:00:00', 'Atlantic Ocean (en route)', -38.217, 0.025, 'saw finbacks; routine sailing; mending', 'fine breezes; fresh breezes later', 'NW by W, then NW', 'SE by E', JSON_ARRAY(), JSON_OBJECT('type','finbacks','action','sightings','result',NULL), 'Sent down mizzen topsail for repair.', 0, 0),
    (@voyage_id, '1842-12-25 00:00:00', 'Atlantic Ocean (en route)', -38.283, 3.000, 'Christmas at sea; sailing in heavy weather', 'fresh breezes; strong gales later', 'WNW, then NW', 'SE by E', JSON_ARRAY(), JSON_OBJECT('type','finbacks','action','sightings','result',NULL), 'Saw plenty of finbacks. Split a topgalant studing sail; hard gale; parted main topsail sheets.', 0, 0),
    (@voyage_id, '1842-12-26 00:00:00', 'Atlantic Ocean (en route)', -38.850, 7.783, 'routine sailing; mending', 'hard gales; moderate later', 'NW', 'ESE', JSON_ARRAY(), JSON_OBJECT(), 'Under close reeft Main topsail and foresail; mending spanker.', 0, 0),
    (@voyage_id, '1843-01-01 00:00:00', 'Southern Ocean (en route)', -39.133, 27.317, 'spoke barque; sailing in heavy weather', 'strong gales; fresh gale later', 'S', '', JSON_ARRAY(JSON_OBJECT('name','Emma (Barque)','home_port','New Bedford')), JSON_OBJECT(), 'Double reeft topsails. Spoke Barque Emma, one whale.', 0, 0),
    (@voyage_id, '1843-01-04 00:00:00', 'Southern Ocean (en route)', -40.783, 33.050, 'whaling attempt; saw finbacks', 'light airs; calm later; fine breezes later', 'W, then NNE, then N', 'SSE, then SE', JSON_ARRAY(), JSON_OBJECT('type','right whale / killers / finbacks','action','saw/lowered; saw; saw','result','no success; no action; no action'), 'Could not get fast to right whale. Saw killers. Middle part calm.', 0, 0),
    (@voyage_id, '1843-01-06 00:00:00', 'Southern Ocean (en route)', -42.467, 41.633, 'whaling attempt; mending', 'fine breezes', 'NNE', 'SE', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw/lowered','result','no success'), 'Saw two right whale; sent down the studding sails booms.', 0, 0),
    (@voyage_id, '1843-01-11 00:00:00', 'Southern Ocean (near Crozets)', -43.917, 48.583, 'spoke barque; routine sailing', 'thick fog; fine breezes with fog later', 'N, then NW', '', JSON_ARRAY(JSON_OBJECT('name','Emma (Barque)','home_port','New Bedford')), JSON_OBJECT(), 'Spoke Barque Emma, six months out with two whale.', 0, 0),
    (@voyage_id, '1843-01-14 00:00:00', 'Southern Ocean (near Crozets)', -44.283, 49.000, 'whaling area activity; made sail', 'hard gales; calm later; light breeze later', 'W, then NW', '', JSON_ARRAY(JSON_OBJECT('name','four ships','home_port',NULL)), JSON_OBJECT(), 'Four sail in sight. Two boiling.', 0, 0),
    (@voyage_id, '1843-01-15 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.500, 49.150, 'whaling attempt; spoke ships', 'light breezes; fresh gales later; moderate later', 'NW', '', JSON_ARRAY(JSON_OBJECT('name','Ontario','home_port','Sag Harbor'), JSON_OBJECT('name','Phenix','home_port','Sag Harbor')), JSON_OBJECT('type','right whale','action','saw/lowered','result','no success'), 'Nine sail in sight. Spoke Ontario (7 whale). Spoke Phenix (8 whale).', 0, 0),
    (@voyage_id, '1843-01-16 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.500, 49.200, 'whaling attempt; spoke ship', 'light breezes; calm later; fresh breezes later; hard gale later', 'NE', '', JSON_ARRAY(JSON_OBJECT('name','Halceon','home_port','New London')), JSON_OBJECT('type','whale (right/sperm)','action','saw/lowered','result','no success'), 'Seven ships in sight. Spoke Halceon (3 whale).', 0, 0),
    (@voyage_id, '1843-01-17 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.500, 49.200, 'whaling attempt', 'fresh gales; thick rainy weather; thick fog later', 'NE', '', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT('type','whale (right/sperm)','action','lowered/got fast','result','irons drawed (lost)'), 'Two sail in sight.', 0, 0),
    (@voyage_id, '1843-01-19 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.617, 49.417, 'saw whale; spoke ships', 'fresh gales', 'NW, then WNW', '', JSON_ARRAY(JSON_OBJECT('name','Ontario','home_port','Sag Harbor'), JSON_OBJECT('name','Monmouth (Barque)','home_port','Greenport'), JSON_OBJECT('name','three other ships','home_port',NULL)), JSON_OBJECT('type','right whale','action','saw','result',NULL), 'Four sail in sight; blowing a hard gale later.', 0, 0),
    (@voyage_id, '1843-01-20 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.533, 49.400, 'saw whale; spoke ship', 'hard gales; fresh gales later; fog later', 'WNW, then N', '', JSON_ARRAY(JSON_OBJECT('name','Ontario','home_port','Sag Harbor')), JSON_OBJECT('type','whale (right/sperm)','action','saw/going quick','result',NULL), 'Laying too under double reeft main topsail and foresail. Seven sail in sight.', 0, 0),
    (@voyage_id, '1843-01-21 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.700, 49.483, 'whaling attempt', 'fresh gales', 'N', '', JSON_ARRAY(), JSON_OBJECT('type','whale (right/sperm)','action','saw/lowered; struck','result','no success; took the line (lost later)'), 'Did not succeed in getting fast, then struck one and took the line.', 0, 0),
    (@voyage_id, '1843-01-23 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.500, 49.450, 'whaling attempt; spoke ship', 'hard gales; moderate later', 'SW', '', JSON_ARRAY(JSON_OBJECT('name','Candace','home_port','New London')), JSON_OBJECT('type','whale (right/sperm)','action','saw/lowered','result','no success'), 'Five sail in sight; eight sail in sight at daylight. Spoke Candace (5 whale).', 0, 0),
    (@voyage_id, '1843-01-24 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.517, 49.633, 'took whale; cut in; boiling; whaling attempt; spoke barque', 'fine breezes', 'NNW, then NW', '', JSON_ARRAY(JSON_OBJECT('name','Phenix (Barque)','home_port','Sag Harbor')), JSON_OBJECT('type','whale (right/sperm)','action','lowered/got fast/took alongside; saw/lowered','barrels',65,'result','successful; no success'), 'Turned him up and took him to the ship. Employed boiling. Spoke Phenix (10 whale).', 0, 0),
    (@voyage_id, '1843-01-25 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.750, 49.717, 'whaling attempt; boiling', 'fresh breezes; hard gales later', 'NW, then N', '', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL), JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT('type','whale (right/sperm)','action','saw/lowered','result','no success'), 'Two sail in sight. Boiling.', 0, 0),
    (@voyage_id, '1843-01-26 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.833, 49.800, 'whaling attempt (too rugged); spoke ship', 'fresh gales; hard gales later', 'N', '', JSON_ARRAY(JSON_OBJECT('name','Arunaut','home_port','Mystic')), JSON_OBJECT('type','whale (right/sperm)','action','saw/too ruggard to lower','result',NULL), 'Saw whale. Spoke Arunaut (11 whale). Two sail in sight.', 0, 0),
    (@voyage_id, '1843-01-28 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.867, 49.850, 'finished stowing; close reefed topsail', 'hard gales', 'N', '', JSON_ARRAY(), JSON_OBJECT(), 'Finished stowing.', 0, 0),
    (@voyage_id, '1843-01-29 00:00:00', 'Southern Ocean (whaling on Crozets)', -44.767, 49.917, 'spoke ship', 'hard gales; moderate later', 'NW', '', JSON_ARRAY(JSON_OBJECT('name','John Elizebeth','home_port','New London')), JSON_OBJECT(), 'Two sail in sight at daylight. Spoke John Elizebeth (9 whale).', 0, 0),
    (@voyage_id, '1843-01-30 00:00:00', 'Southern Ocean (departing Crozets)', -44.750, 49.950, 'whaling attempt; departed', 'light breezes; fresh gales later', 'N, then NE', 'E by S, then ESE', JSON_ARRAY(), JSON_OBJECT('type','whale (right/sperm)','action','saw/lowered','result','no success'), 'Made all sail. Bound off for the NW. Coast. Double reeft the topsails.', 0, 0),
    (@voyage_id, '1843-02-11 00:00:00', 'Southern Ocean (en route)', -43.650, 95.167, 'whaling attempt', 'fresh breezes; light breezes later', 'SW, then W', 'SE by E', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw/lowered/got fast/sounded/cut away','result','lost'), 'Lost two lances, three irons and 30 fathoms of line. Cut away line after whale sounded and got foul.', 0, 0),
    (@voyage_id, '1843-02-23 00:00:00', 'Southern Ocean (near Australia)', -48.083, 141.250, 'made sail; employed getting anchor on the bow', 'fresh breezes; light breezes later; very green water', 'NE, then WSW, then W', 'E 1/2 S', JSON_ARRAY(), JSON_OBJECT(), 'Water very green supposed to be on soundings. Employed getting the starboard anchor on the bow.', 0, 0),
    (@voyage_id, '1843-02-28 00:00:00', 'Southern Ocean (gale)', -46.867, 155.667, 'severe weather; lost boat', 'hard gales; heavy gale later', 'W', 'E, then N, then E by S', JSON_ARRAY(), JSON_OBJECT(), 'Lost the waist boat by a sea. Brought the ship too heading to the northward. Took in the bow boat.', 0, 0),
    (@voyage_id, '1843-03-03 00:00:00', 'Auckland Islands (approach)', -50.500, 165.333, 'made land; sailing in heavy weather', 'thick weather and rain; fresh gales', '', 'E, then ESE', JSON_ARRAY(), JSON_OBJECT(), 'Brought the ship too under a close reeft main topsail. Aucklands group 30 miles distant.', 0, 0),
    (@voyage_id, '1843-03-04 00:00:00', 'Auckland Islands (attempted entry)', -50.700, 166.000, 'attempted harbor entry; sighted smoke', 'fresh breezes; light winds later; heavy squalls later', 'W', 'E by S, then off ENE', JSON_ARRAY(), JSON_OBJECT(), 'Got soundings 13 fins. Saw smoke on shore. Got blowed out of the bay. Supposed to be a ships crew cast away.', 0, 0),
    (@voyage_id, '1843-03-06 00:00:00', 'Pacific Ocean (en route from NZ area)', -48.183, 172.100, 'split sail; saw whales', 'thick weather; heavy rain squalls; fresh gales', 'W, then N', 'NE, then NE', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw/too ruggard to lower','result',NULL), 'Split the fore topsail in a squall. Saw several right whale.', 0, 0),
    (@voyage_id, '1843-03-07 00:00:00', 'Pacific Ocean (en route)', -46.217, 175.100, 'routine sailing; saw comet', 'strong gales', 'W', 'NE', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Saw one sail. Saw a very large comet in the NW at 7:50 PM.', 0, 0),
    (@voyage_id, '1843-03-08 00:00:00', 'Pacific Ocean (en route)', -44.217, 178.817, 'spoke ships', 'fresh gales', 'W', 'NE', JSON_ARRAY(JSON_OBJECT('name','Fanney','home_port','Sag Harbor'), JSON_OBJECT('name','Vermont (Barque)','home_port','Perkipsy')), JSON_OBJECT(), 'Spoke Fanney (2600 BBLS oil). Spoke Vermont (2500 BBLS).', 0, 0),
    (@voyage_id, '1843-03-09 00:00:00', 'Pacific Ocean (en route)', -44.267, -177.450, 'routine sailing', 'fresh breezes', 'W, then NW', 'ENE, then E by S', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1843-03-09 16:00:00', 'Chatham Islands', -44.667, -176.167, 'made land; whaling — took two whales', 'fresh breezes', 'WSW', '', JSON_ARRAY(), JSON_OBJECT('type','sperm whale','action','saw/lowered/got fast/turned up/took alongside','barrels',NULL,'result','successful'), 'Made the Chatham Islands; two large sperm whale alongside. Log entry is for the day, but location change and time suggest a significant event time.', 0, 0),
    (@voyage_id, '1843-03-10 00:00:00', 'Chatham Islands (cutting in)', -44.867, -175.750, 'cutting in; lost whale head', 'light airs; fresh breezes later; fresh gale later', 'NW', '', JSON_ARRAY(), JSON_OBJECT('type','sperm whale','action','cutting; cut from the head','result','lost head/processing'), 'Got in one whales body; blowing a fresh gale from NW, could not save the head.', 0, 0),
    (@voyage_id, '1843-03-11 00:00:00', 'Pacific Ocean (boiling)', -45.583, -174.867, 'finished cutting; boiling', 'fresh gales; light airs later; hard gale later', 'NW, then N', '', JSON_ARRAY(), JSON_OBJECT('type','whale (sperm)','action','finished cutting; boiling','result','processing'), 'Finished cutting the second whale. Employed boiling. Note: Longitude may be a transcription error (144.52 W is far east of Chatham Is).', 0, 0),
    (@voyage_id, '1843-03-13 00:00:00', 'Pacific Ocean (finished boiling)', -42.667, -172.667, 'finished boiling', 'light breezes; fine weather', 'S', '', JSON_ARRAY(), JSON_OBJECT(), 'Finished boiling.', 0, 0),
    (@voyage_id, '1843-03-15 00:00:00', 'Pacific Ocean (stowing oil)', -41.667, -170.317, 'finished stowing; repairing sails', 'light breezes; light airs and calms later', 'E', '', JSON_ARRAY(), JSON_OBJECT('type','sperm oil','action','finished stowing','barrels',106,'result','on board'), 'Finished stowing 106 BBLS of sperm oil. Employed repairing sails.', 0, 0),
    (@voyage_id, '1843-03-18 00:00:00', 'Pacific Ocean (en route)', -36.000, -165.217, 'carried away yard; mending', 'light breezes; fresh breezes later; fresh breezes with rain squalls later', 'WSW, then WNW', 'NNE, then NE by N', JSON_ARRAY(), JSON_OBJECT(), 'Carried away the mizzen topsail yard; used the spritsail yard for a mizzen topsail yard.', 0, 0),
    (@voyage_id, '1843-04-04 00:00:00', 'Oaitipeha Bay, Tahiti (arrival)', -17.833, -149.500, 'arrived in port; took pilot; anchored', 'fine breezes; baffling winds with heavy rain squalls later; fine breezes later', 'ENE, then NE', 'in for Otaheite Harbour', JSON_ARRAY(), JSON_OBJECT(), 'Beating up for harbor. Came to anchor in Oaitipeha Bay. Took a pilot. 10 sail in the harbour.', 0, 0),
    (@voyage_id, '1843-04-10 00:00:00', 'Oaitipeha Bay, Tahiti (in port)', -17.833, -149.500, 'ran-away crewman; shipped natives; preparing for sea', '', '', '', JSON_ARRAY(), JSON_OBJECT(), 'Alexander Read ran from the ship. Shipped two Otaheite Natives. Nine sail in the harbour.', 0, 0),
    (@voyage_id, '1843-04-11 00:00:00', 'Oaitipeha Bay, Tahiti (departing)', -17.833, -149.500, 'departed port; preparing for sea', 'fine breezes', 'SE', 'NNE', JSON_ARRAY(), JSON_OBJECT(), 'Pilot came on board; got the ship underway.', 0, 0),
    (@voyage_id, '1843-04-12 00:00:00', 'Pacific Ocean (en route)', -14.500, -149.733, 'carried away yard; stowed anchors and cables', 'fine breezes', 'SE', 'NNE', JSON_ARRAY(), JSON_OBJECT(), 'Carried away the fore topgalant yard. Sent another yard aloft. Stowed the anchors and cables.', 0, 0),
    (@voyage_id, '1843-04-15 00:00:00', 'Pacific Ocean (near Caroline Islands)', -8.367, -149.800, 'made land; routine sailing', 'light breezes; fine breezes later', 'E', 'NNE', JSON_ARRAY(), JSON_OBJECT(), 'Saw the land (Caroline Islands) bearing west 18 miles distant.', 0, 0),
    (@voyage_id, '1843-04-17 00:00:00', 'Pacific Ocean (en route)', -2.717, -149.717, 'blacksmith splicing lances; crew employed in rigging', 'fine breezes', 'ESE', 'N by E', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0);

-- ───────────────────────────────────────────────────────────────
-- Seed: Events (Indian Chief, April 1843 - September 1843)
-- Continues from previous event set (from Tahiti)
-- ───────────────────────────────────────────────────────────────
INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_id, '1843-04-19 00:00:00', 'Pacific Ocean (en route to NW Coast)', 0.750, -149.933, 'employed setting up the rigging; carpenter making skylight', 'light winds', 'ESE', 'N by E', JSON_ARRAY(), JSON_OBJECT(), '45 miles north. Latitude is likely positive North, as they departed Tahiti/Society Islands (South).', 0, 0),
    (@voyage_id, '1843-04-20 00:00:00', 'Pacific Ocean (en route)', 2.100, -150.917, 'employed setting up rigging', 'fine breezes', 'ESE', 'N 1/2 E', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1843-04-22 00:00:00', 'Pacific Ocean (en route)', 5.333, -150.800, 'breaking out and coopering provision', 'light breezes', 'E, then E by N', 'NNE', JSON_ARRAY(), JSON_OBJECT(), 'Three sixties of molasses leaked out. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-04-24 00:00:00', 'Pacific Ocean (en route)', 9.833, -152.033, 'coopering and stowing provision', 'fresh breezes', 'NE', 'NNW', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1843-04-26 00:00:00', 'Pacific Ocean (en route)', 15.167, -154.167, 'stowing provision; sailing in heavy weather', 'strong breezes; fresh gales later with hard squalls', 'NE', 'NNW', JSON_ARRAY(), JSON_OBJECT(), 'Double reeft the topsails at 6 PM.', 0, 0),
    (@voyage_id, '1843-04-28 00:00:00', 'Off Owhyhee (Hawaii)', 19.500, -156.417, 'made land; sailing in heavy weather', 'strong breezes; heavy squalls later; light winds later', 'E, then N by W', 'NNW; NW by N 1/2 N', JSON_ARRAY(), JSON_OBJECT(), 'Made Owhyhee (Hawaii) one of the Sandwich Islands at 6 PM. Took in mainsail and double reeft the topsails.', 0, 0),
    (@voyage_id, '1843-04-29 00:00:00', 'Off Maui (Sandwich Islands)', 20.000, -156.417, 'saw Mowee; spoke brig', 'light winds; variable winds later; fresh breezes later', 'S; NE to S by W; NE', 'standing in for Mowee', JSON_ARRAY(JSON_OBJECT('name','brig','home_port',NULL)), JSON_OBJECT(), 'Owhyhee bearing ESE. Saw Mowee (Maui) bearing NE 20 miles dist.', 0, 0),
    (@voyage_id, '1843-04-30 00:00:00', 'Off Oahu (Sandwich Islands)', 21.333, -157.833, 'whaling attempt; made sail for harbour', 'calm; strong breeze later; fresh breezes later', 'NE; E; NW', 'W by N 1/2 N; standing in for the harbour', JSON_ARRAY(JSON_OBJECT('name','two sail','home_port',NULL)), JSON_OBJECT('type','sperm whales','action','saw/lowered','result','no success'), 'Saw Ranai (Lanai) and Morotoi (Molokai). Saw Woahoo (Oahu). Whales going quick to windward.', 0, 0),
    (@voyage_id, '1843-05-01 00:00:00', 'Off Oahu (departed)', 22.967, -159.100, 'captain ashore for news/information; made sail', 'fresh breezes', 'NE', 'W by N to clear the land', JSON_ARRAY(JSON_OBJECT('name','English man of war','home_port','England'), JSON_OBJECT('name','two French whalers','home_port','France')), JSON_OBJECT(), 'Captain went on shore at the Town of Woahoo. 7 sail in the harbour.', 0, 0),
    (@voyage_id, '1843-05-03 00:00:00', 'Pacific Ocean (en route to NW Coast)', 27.133, -160.167, 'stowing passage water and caulking ship', 'fine breezes', 'NE', 'NNE', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1843-05-09 00:00:00', 'Pacific Ocean (en route)', 37.250, -159.500, 'employed shifting sails; routine sailing', 'fresh breezes; fine breezes later', 'W; SW', 'N', JSON_ARRAY(), JSON_OBJECT(), 'Green water and no fish.', 0, 0),
    (@voyage_id, '1843-05-12 00:00:00', 'Pacific Ocean (en route)', 38.633, -158.983, 'saw finbacks; lowered for sunfish', 'light airs with calms', '', '', JSON_ARRAY(), JSON_OBJECT('type','finbacks/sunfish','action','saw/lowered','result','no success on sunfish'), '', 0, 0),
    (@voyage_id, '1843-05-13 00:00:00', 'Pacific Ocean (en route)', 39.500, -158.950, 'whaling attempt; made sail', 'calm; light airs later; fine breezes later', 'SE', 'N by W', JSON_ARRAY(), JSON_OBJECT('type','sulfur bottoms','action','lowered','result','no success'), 'Sulfur bottoms is a common name for Blue or Fin Whales.', 0, 0),
    (@voyage_id, '1843-05-14 00:00:00', 'Pacific Ocean (en route)', 40.850, -149.133, 'saw finbacks', 'fine breezes; light air with calms later', 'SE', 'N by W 1/2 W', JSON_ARRAY(), JSON_OBJECT('type','finbacks','action','sightings','result',NULL), 'Ends with calms.', 0, 0),
    (@voyage_id, '1843-05-19 00:00:00', 'Pacific Ocean (NW Ground approach)', 47.833, -158.617, 'whaling attempt; lost irons', 'light breezes', 'NW', '', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','lowered/got fast to two','result','drawed from one, cut off from other/lost two irons'), 'Lost two irons. Whale took the line to windward, could not bring him to.', 0, 0),
    (@voyage_id, '1843-05-24 00:00:00', 'Pacific Ocean (NW Ground)', 53.167, -154.000, 'took whale; commenced cutting', 'fine weather with light breezes', 'S', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/got fast/turned up/took alongside/began to cut','barrels',NULL,'result','successful'), 'Lowered, line parted. Later, another boat struck, turned him up, and took him to the ship. 8 barrels noted (likely a visual/scribble, not precise measure).', 0, 0),
    (@voyage_id, '1843-05-25 00:00:00', 'Pacific Ocean (NW Ground)', 53.333, -153.850, 'took whale; prepared for cutting; boiling', 'light breezes; fine breezes later', 'S', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered/struck/turned up/took alongside','barrels',NULL,'result','successful'), 'Prepared for cutting. Boiling.', 0, 0),
    (@voyage_id, '1843-05-27 00:00:00', 'Pacific Ocean (NW Ground)', 53.567, -153.567, 'cutting in; boiling', 'fine breezes; fresh breezes later', 'SSW', '', JSON_ARRAY(), JSON_OBJECT(), 'Took in the head, throat, and lips. Finished cutting. Boiling.', 0, 0),
    (@voyage_id, '1843-05-28 00:00:00', 'Pacific Ocean (NW Ground)', 53.300, -152.733, 'stowing and boiling; saw whale', 'fine breezes; fresh breezes later; fine weather later', 'NW', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw','result',NULL), 'Blubber room full and blubber on deck. Commenced stowing at 3:30 AM.', 0, 0),
    (@voyage_id, '1843-05-29 00:00:00', 'Pacific Ocean (NW Ground)', 53.767, -152.767, 'finished stowing (189 Bbls); whaling attempt; boiling', 'fresh breezes; fine weather later', 'NW', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered','barrels',189,'result','finished stowing; no success'), 'Finished stowing 189 Bbls of oil. Saw whale, lowered, no success. Boiling.', 0, 0),
    (@voyage_id, '1843-05-30 00:00:00', 'Pacific Ocean (NW Ground)', 53.533, -151.800, 'took whale; finished stowing (126 Bbls); cutting in; boiling', 'fine breezes', 'N', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/turned up/took alongside/cut in','barrels',126,'result','successful'), 'Finished stowing 126 Bbls oil. Boiling and cutting.', 0, 0),
    (@voyage_id, '1843-05-31 00:00:00', 'Pacific Ocean (NW Ground)', 53.733, -152.117, 'finished cutting; saw whales; boiling', 'fine breezes; light breezes later; calm later', 'NNE', '', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw several','result',NULL), 'Finished cutting. Several right whale in sight. Boiling.', 0, 0),
    (@voyage_id, '1843-06-01 00:00:00', 'Pacific Ocean (NW Ground)', 53.750, -152.000, 'whaling attempt; stowing (74 Bbls); boiling', 'light breezes', 'W', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered','barrels',74,'result','no success'), 'Darted mizzen (likely a typo for missed). Stowed 74 Bbls main hatch. Boiling and stowing.', 0, 0),
    (@voyage_id, '1843-06-06 00:00:00', 'Pacific Ocean (NW Ground)', 53.800, -150.000, 'whaling attempt (struck and sunk/boat capsized); spoke ships', 'fresh breezes', 'SW', '', JSON_ARRAY(JSON_OBJECT('name','Main','home_port','Fairhaven'), JSON_OBJECT('name','3 other sail','home_port',NULL)), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/capsised one boat/sunk','result','lost whale and boat damaged'), 'Struck, capsized one boat, turned him up and he sunk. Came on to blow hard. Main of Fairhaven (70 bbls sperm).', 0, 0),
    (@voyage_id, '1843-06-09 00:00:00', 'Pacific Ocean (NW Ground)', 55.250, -148.183, 'spoke ship; routine sailing', 'fresh gales; fresh gales later', 'SE', '', JSON_ARRAY(JSON_OBJECT('name','Maine','home_port','Fair Haven')), JSON_OBJECT(), 'Spoke Maine of Fair Haven (70 bbls of sperm). Longitude corrected to W.', 0, 0),
    (@voyage_id, '1843-06-11 00:00:00', 'Pacific Ocean (NW Ground)', 54.567, -151.000, 'took whale; cut in; whaling attempt (struck and sunk)', 'light breezes; clear weather later; thick fog later', 'SE', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/turned up/took alongside/cut in; lowered/struck/sunk','result','successful; lost whale'), 'Turned him up and took him to the ship. Saw whale, lowered, struck, turned him up and he sunk. Shut in fog. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-06-14 00:00:00', 'Pacific Ocean (NW Ground)', 54.000, -151.733, 'finished stowing (151 Bbls)', 'fresh breezes; fog', 'SE', '', JSON_ARRAY(), JSON_OBJECT(), 'Finished stowing 151 Bbls of oil fore hold.', 0, 0),
    (@voyage_id, '1843-06-15 00:00:00', 'Pacific Ocean (NW Ground)', 54.233, -151.883, 'took two whales (one dry skin); boat stove', 'light breezes; fog with rain later; clear weather later', 'E', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/took alongside/cut in/let body go; lowered/struck/took in tow','result','successful (dry skin); successful (boat stove)'), 'First whale proved to be a dry skin (very little oil). Waist boat got stove on the second whale. Employed boiling.', 0, 0),
    (@voyage_id, '1843-06-20 00:00:00', 'Pacific Ocean (NW Ground)', 55.067, -151.767, 'spoke ship; whaling attempts (boatsteerer struck/sunk); hard luck', 'fresh breezes', 'S', '', JSON_ARRAY(JSON_OBJECT('name','Logan','home_port','New Bedford')), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck; lowered/struck/sunk; lowered/struck/sunk','result','missed; lost whale; lost whale'), 'Spoke Logan (1900 Bbls). William Glass boatsteerer got struck by the whale and knocked overboard (safe). Ends Day with hard luck.', 0, 0),
    (@voyage_id, '1843-07-01 00:00:00', 'Pacific Ocean (NW Ground)', 54.133, -150.333, 'spoke ship; whaling attempt', 'fresh gales; moderate weather later; fine breezes later', 'N', 'SSW', JSON_ARRAY(JSON_OBJECT('name','Thomas Williams','home_port','Stonington')), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered','result','no success'), 'Spoke Thomas Williams (1200 Bbls).', 0, 0),
    (@voyage_id, '1843-07-06 00:00:00', 'Pacific Ocean (NW Ground)', 53.667, -150.550, 'whaling attempts (lost line/irons)', 'fresh breezes; fresh gales later', 'SW', 'south', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/ran to windward/second boat struck/cut off; lowered/struck/line parted','result','lost line/3 irons; line parted'), 'Lost one line and three irons. Came on thick fog.', 0, 0),
    (@voyage_id, '1843-07-07 00:00:00', 'Pacific Ocean (NW Ground)', 53.300, -150.400, 'spoke ship; took whale', 'fresh breezes; thick fog; calm later', 'SW', '', JSON_ARRAY(JSON_OBJECT('name','Henery Lee','home_port','Sagharbour')), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/turned up/took alongside','barrels',NULL,'result','successful'), 'Spoke Henery Lee (1200 Bbls oil). Came on fog. Turned him up and took him to the ship.', 0, 0),
    (@voyage_id, '1843-07-10 00:00:00', 'Pacific Ocean (NW Ground)', 53.000, -150.633, 'whaling attempt (struck and cut off); stowing (220 Bbls)', 'fresh breezes; blowing a gale later', 'SE, then S', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/cut off','result','lost whale'), 'Whale ran to windward, cut off. Employed stowing 220 Bbls oil in the fore hold.', 0, 0),
    (@voyage_id, '1843-07-13 00:00:00', 'Pacific Ocean (NW Ground)', 53.500, -150.000, 'whaling attempt; took whale', 'fresh breezes; fog', 'S', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/drawed; lowered/struck/turned up','result','no success; successful'), 'Saw whale close to the ship. Struck and drawed. Lowered and struck another, turned him up at noon. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-07-15 00:00:00', 'Pacific Ocean (NW Ground)', 53.333, -150.000, 'whaling attempt (line cut off by accident); boiling', 'light breezes; fresh breezes later', 'E', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/line cut off by accident','result','lost whale/lost 2 lances and 4 harpoons'), 'Lost two lances and four harpoons in the whale. Two men sick. Employed boiling. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-07-17 00:00:00', 'Pacific Ocean (NW Ground)', 53.000, -150.000, 'whaling attempts (cut off/line parted); spoke ship; stowing', 'light breezes', '', '', JSON_ARRAY(JSON_OBJECT('name','Henery Lee','home_port','Sagharbour')), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/cut off; lowered/struck/line parted','result','lost whale/foul line; line parted'), 'Struck, whale sounded, got foul line, had to cut off. Spoke Henery Lee (1400 bbls). Employed stowing. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-07-18 00:00:00', 'Pacific Ocean (NW Ground)', 52.500, -148.683, 'stowing (164 Bbls); heavy weather', 'fresh gales; blowing a hard gale later', 'WSW', '', JSON_ARRAY(JSON_OBJECT('name','six sail','home_port',NULL)), JSON_OBJECT(), 'Stowed 164 Bbls in after hold. Laying too under double reeft main topsail and foresail.', 0, 0),
    (@voyage_id, '1843-07-21 00:00:00', 'Pacific Ocean (NW Ground)', 52.983, -149.150, 'spoke ships; saw whale; cleaning bone', 'fresh breezes', 'S', '', JSON_ARRAY(JSON_OBJECT('name','Ship','home_port','New Bedford'), JSON_OBJECT('name','Henry Lee','home_port','Sagharbor'), JSON_OBJECT('name','Julian','home_port','New Bedford')), JSON_OBJECT('type','whale (species not stated)','action','saw/going quick','result',NULL), 'Spoke Ship of New Bedford (1300 Bbls) and Julian (2200 Bbls). 7 Sail in Sight. Employed cleaning bone.', 0, 0),
    (@voyage_id, '1843-07-23 00:00:00', 'Pacific Ocean (NW Ground)', 52.383, -151.567, 'spoke ships; whaling attempt (line parted); blowing gale', 'fresh breezes; blowing a gale later', 'NNW, then S', 'W by S', JSON_ARRAY(JSON_OBJECT('name','Erie','home_port','Fair Haven'), JSON_OBJECT('name','Catchalot (French Ship)','home_port','Harver')), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/line parted/gave chase/gave up','result','lost whale/line parted'), 'Spoke Erie (1100 Bbls Sperm, 1200 Whale) and French Ship Catchalot (2500 Bbls).', 0, 0),
    (@voyage_id, '1843-07-27 00:00:00', 'Pacific Ocean (NW Ground)', 52.500, -152.867, 'took two whales; employed cutting', 'fine breezes; fog', '', '', JSON_ARRAY(JSON_OBJECT('name','seven sail','home_port',NULL)), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/turned up/took alongside (x2)','barrels',NULL,'result','successful'), 'Took two whales. Employed cutting. 7 Sail in Sight. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-07-29 00:00:00', 'Pacific Ocean (NW Ground)', 52.533, -152.667, 'spoke barque; boiling; trade', 'calms; fog', '', '', JSON_ARRAY(JSON_OBJECT('name','Eugene (Barque)','home_port','Stonington')), JSON_OBJECT(), 'Spoke Barque Eugene (2100 Bbls). Bought a new set of cutting falts (blocks/ropes). Employed boiling.', 0, 0),
    (@voyage_id, '1843-07-31 00:00:00', 'Pacific Ocean (NW Ground)', 52.667, -151.733, 'finished stowing (184 Bbls); boiling', 'fresh breezes; fresh breezes later', 'SE, then W', '', JSON_ARRAY(), JSON_OBJECT(), 'Finished stowing 184 Bbls. Employed stowing and boiling.', 0, 0),
    (@voyage_id, '1843-08-03 00:00:00', 'Pacific Ocean (NW Ground)', 52.500, -155.333, 'took whale; commenced cutting', 'hard gales; moderate later', 'NE', 'WSW', JSON_ARRAY(JSON_OBJECT('name','sail','home_port',NULL)), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered/struck/turned up/took alongside/commenced cutting','result','successful'), 'Whales around the ship. Cutting.', 0, 0),
    (@voyage_id, '1843-08-04 00:00:00', 'Pacific Ocean (NW Ground)', 52.500, -155.400, 'finished cutting (poor oil); saw whale', 'light breezes; fine breezes later; fresh breezes later', 'NE', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','finished cutting; saw/going to windward','result','very poor oil'), 'Finished cutting. Whale proved to be very poor (little oil, plenty of water).', 0, 0),
    (@voyage_id, '1843-08-06 00:00:00', 'Pacific Ocean (NW Ground)', 52.500, -156.867, 'spoke ship; whaling attempt (lost 4 irons/2 lines); heavy weather', 'fine breezes; fresh breezes later; blowing a gale later', 'WSW, then SSW, then SE', '', JSON_ARRAY(JSON_OBJECT('name','Tuskeny','home_port','Sagharbor')), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck with two boats/sounded out the lines/went off','result','lost whale/4 irons/2 lines'), 'Spoke Tuskeny (1200 Bbls oil). Came on to blow a gale from the SE. Double reeft topsails.', 0, 0),
    (@voyage_id, '1843-08-14 00:00:00', 'Pacific Ocean (NW Ground)', 52.833, -153.850, 'took whale', 'fine breezes', 'W', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw/chased; lowered/struck/turned up/took alongside','result','no success; successful'), 'Saw whale, chased, no success. Later, lowered, struck, turned him up and took him to the ship.', 0, 0),
    (@voyage_id, '1843-08-15 00:00:00', 'Pacific Ocean (NW Ground)', 52.833, -154.383, 'took whale; cutting and boiling', 'light breezes', 'W, then SE', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','cutting; saw/lowered/struck/turned up/took alongside','result','successful'), 'Finished cutting and began to boil. Struck and took another whale to the ship. Longitude corrected to 154.383 W.', 0, 0),
    (@voyage_id, '1843-08-19 00:00:00', 'Pacific Ocean (NW Ground)', 52.767, -155.600, 'whaling attempt (struck and cut off); stowing', 'light breezes; thick with rain later', 'SE, then W', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','boats off in chase/struck/cut from the whale in the fog','result','lost whale'), 'Struck the whale, came on thick fog, lost sight of the ship. Found the ship, cut from the whale. Employed stowing.', 0, 0),
    (@voyage_id, '1843-08-20 00:00:00', 'Pacific Ocean (NW Ground)', 52.700, -155.000, 'whaling attempts (sunk/line taken); boat stove', 'light breezes; fine breezes later; blowing a gale later', 'W, then S, then SE', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','lowered/struck/starboard boat got stove/sunk; lowered/struck/took the line','result','lost whale; lost line/stowing'), 'Starboard boat got stove. Turned him up and he sunk. Struck another, he sounded and took the line. Came on to blow a gale.', 0, 0),
    (@voyage_id, '1843-08-23 00:00:00', 'Pacific Ocean (NW Ground)', 53.333, -154.167, 'spoke ship; whaling attempt', 'fresh gales; fresh breezes later', 'SW', '', JSON_ARRAY(JSON_OBJECT('name','May Flower','home_port','New Bedford')), JSON_OBJECT('type','whale (species not stated)','action','saw/too ruggard to lower; lowered/chased','result','no success'), 'Spoke May Flower (2200 Bbls). Boats off in chase.', 0, 0),
    (@voyage_id, '1843-08-24 00:00:00', 'Pacific Ocean (NW Ground)', 53.317, -154.500, 'took whale; cutting; whaling attempt', 'fresh breezes; light breezes later', 'S', '', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','struck/turned up/took alongside/cutting; saw/lowered','result','successful; no success'), 'Finished cutting. Boats off in chase.', 0, 0),
    (@voyage_id, '1843-08-28 00:00:00', 'Pacific Ocean (NW Ground)', 52.717, -153.367, 'stowing (in steerage); boiling', 'fresh gales', 'S', '', JSON_ARRAY(), JSON_OBJECT(), 'Employed stowing in the steerage. Latitude is corrected to 52.717 N.', 0, 0),
    (@voyage_id, '1843-09-02 00:00:00', 'Pacific Ocean (Departed NW Coast)', 51.650, -150.000, 'bound off the NW Coast; scrubbing bone', 'light breezes; calm later; light breezes later', 'W, then E', 'ESE', JSON_ARRAY(), JSON_OBJECT('type','sulfur bottoms','action','saw a number','result',NULL), 'Bound off the NW Coast with 2500 Bbls of oil.', 0, 0),
    (@voyage_id, '1843-09-04 00:00:00', 'Pacific Ocean (en route)', 50.050, -150.167, 'spoke ship; took whale (boatsteerer struck)', 'light breezes; light breezes later', 'E, then W', '', JSON_ARRAY(JSON_OBJECT('name','Julyan','home_port','New Bedford')), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered/struck/struck the boat/took alongside','result','successful'), 'Spoke Julyan (2700 Bbls). Whale struck the boat and knocked me overboard, got safe into the boat. Two sail in sight.', 0, 0),
    (@voyage_id, '1843-09-07 00:00:00', 'Pacific Ocean (en route)', 49.900, -149.167, 'whaling attempt (blackfish); heavy weather', 'light breezes; blowing a gale later', 'SE, then S', 'eastward', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','lowered/fast and drawed','result','no success'), 'Lowered for Blackfish, fast and drawed. Came on to blow a gale. Employed bending a main topsail.', 0, 0),
    (@voyage_id, '1843-09-09 00:00:00', 'Pacific Ocean (en route)', 47.933, -148.500, 'saw blackfish; whaling attempt; stowing', 'hard gales; more moderate later; light breezes later', 'SW, then W, then SW', 'SE by S, then SSE', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','saw/lowered/struck','result','iron drawed (lost)'), 'Wind hauled to the west. Struck iron drawed. Employed stowing.', 0, 0),
    (@voyage_id, '1843-09-25 00:00:00', 'Off Hawaii', 20.933, -155.283, 'made land', 'fresh breezes; strong breezes later', 'ENE', 'SW by S', JSON_ARRAY(), JSON_OBJECT(), 'Made the Island of Owhyhee (Hawaii). Made the Island of Mowee (Maui) bearing west 40 miles dist.', 0, 0);

-- ───────────────────────────────────────────────────────────────
-- Seed: Events (Indian Chief, September 1843 - March 1844)
-- Continues from previous event set (Arrival at Sandwich Islands, en route to Cape Horn)
-- ───────────────────────────────────────────────────────────────
-- ───────────────────────────────────────────────────────────────
-- Seed: Events (Indian Chief, September 1843 - March 1844) - COORDINATE CORRECTIONS
-- ───────────────────────────────────────────────────────────────
DELETE FROM events WHERE voyage_id = @voyage_id AND date BETWEEN '1843-09-26 00:00:00' AND '1844-03-01 00:00:00';

INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_id, '1843-09-26 00:00:00', 'Maui Harbour (Sandwich Islands)', 20.880, -156.680, 'arrived at anchor; spoke ship', 'fresh breezes with heavy squalls', 'ENE', 'standing in for Mowee harbour', JSON_ARRAY(JSON_OBJECT('name','George and Susan','home_port','New Bedford')), JSON_OBJECT(), 'Spoke George and Susan (1300 bbls sperm). Brought up in 19 fathoms. 27 sail in the harbour. Lat/Lon estimated for Maui anchorage.', 0, 0),
    (@voyage_id, '1843-09-29 00:00:00', 'Maui Harbour (Sandwich Islands)', 20.880, -156.680, 'at anchor; provisioning; painting', 'fine weather', '', '', JSON_ARRAY(), JSON_OBJECT(), 'Took on board 100 Bbls of water.', 0, 0),
    (@voyage_id, '1843-10-08 00:00:00', 'Maui Harbour (Sandwich Islands)', 20.880, -156.680, 'preparing for sea', 'fine weather', '', '', JSON_ARRAY(), JSON_OBJECT(), 'All hands on shore for the last time. All clear for sea.', 0, 0),
    (@voyage_id, '1843-10-09 00:00:00', 'Maui Harbour (Departed)', 20.880, -156.680, 'hove short; got underway', 'fine weather', '', 'SW', JSON_ARRAY(), JSON_OBJECT(), 'At 9 AM had the ship under way.', 0, 0),
    (@voyage_id, '1843-10-10 00:00:00', 'Pacific Ocean (en route to Cape Horn)', 18.750, -156.400, 'in company with ship; stowing anchors', 'fine breezes', '', 'S', JSON_ARRAY(JSON_OBJECT('name','Superior','home_port','New London')), JSON_OBJECT(), 'Longitude estimated.', 0, 0),
    (@voyage_id, '1843-10-16 00:00:00', 'Pacific Ocean (en route)', 7.133, -155.000, 'rigging damage; sail repair', 'fresh breezes with rain squalls; fresh gales later with heavy squalls', 'NE', 'ESE', JSON_ARRAY(), JSON_OBJECT(), 'Squall struck and carried away the jib boom. Took spare main topsail yard for a jib boom. Carpenter employed fitting the boom. Longitude estimated.', 0, 0),
    (@voyage_id, '1843-10-22 00:00:00', 'Pacific Ocean (crossing equator)', -0.283, -155.850, 'routine sailing', 'fine breezes', 'E', 'S to SSE', JSON_ARRAY(), JSON_OBJECT(), '17 miles south (of equator). 3 men sick.', 0, 0),
    (@voyage_id, '1843-10-24 00:00:00', 'Pacific Ocean (whaling attempt)', -3.450, -156.650, 'whaling attempt; mending sails', 'fine breezes; fresh breezes later; light breezes later', 'E', 'SSE', JSON_ARRAY(), JSON_OBJECT('type','sperm whales','action','saw/lowered/chase','result','missed/no success'), 'Saw sperm whales, missed. Employed mending sails. 3 men sick.', 0, 0),
    (@voyage_id, '1843-10-27 00:00:00', 'Pacific Ocean (near Sandy Island)', -7.400, -155.683, 'sighted land; routine sailing; repairing sails', 'fine breezes; fine breezes later', 'NE, then NNW', 'SE by S', JSON_ARRAY(), JSON_OBJECT(), 'Saw Sandy Island bearing SE by E, 15 miles dist. 4 men sick.', 0, 0),
    (@voyage_id, '1843-11-03 00:00:00', 'Near Wateco Island (Society Islands)', -20.050, -156.733, 'made land; saw sail', 'fine breezes; fresh breezes later; light breezes later', 'NE, then N, then NW', 'S by W', JSON_ARRAY(JSON_OBJECT('name','sail','home_port',NULL)), JSON_OBJECT(), 'Made the Island of Wateco (Society Islands). 4 men sick.', 0, 0),
    (@voyage_id, '1843-11-05 00:00:00', 'Near Mangaia Island', -21.783, -158.167, 'made land', 'fine breezes', 'SE', 'SW', JSON_ARRAY(), JSON_OBJECT(), 'Saw the Island of Mangea (Mangaia) bearing SW 30 miles dist. 4 men sick.', 0, 0),
    (@voyage_id, '1843-11-06 00:00:00', 'Near Mangaia Island (trade)', -22.833, -159.450, 'provisioning from canoes; departed', 'fresh breezes', 'SSE, then SSW', 'in for the land, then SW', JSON_ARRAY(), JSON_OBJECT(), 'Five canoes came off to the ship with fruit and war clubs. Made sail steering to the SW. 4 men sick.', 0, 0),
    (@voyage_id, '1843-11-12 00:00:00', 'Pacific Ocean (en route)', -31.117, -163.733, 'spoke ship; breaking out and coopering oil', 'fine breezes', 'NE', 'S', JSON_ARRAY(JSON_OBJECT('name','Magnolia','home_port','New Bedford')), JSON_OBJECT(), 'Spoke Magnolia (2300 Bbls). 4 men sick.', 0, 0),
    (@voyage_id, '1843-11-16 00:00:00', 'Pacific Ocean (whaling ground)', -35.933, -161.333, 'took whale; commenced cutting; saw whales', 'light breezes; fine breezes later', 'N, then W, then NE', 'SE', JSON_ARRAY(), JSON_OBJECT('type','right whale','action','saw/lowered/struck/turned up/took alongside/cutting','barrels',NULL,'result','successful'), 'Saw four right whale. Took one. Employed boiling.', 0, 0),
    (@voyage_id, '1843-11-18 00:00:00', 'Pacific Ocean (boiling/took dead whale)', -36.500, -160.000, 'finished boiling; took dead whale; cutting/boiling', 'light breezes; fine breezes later', 'E, then NE', 'SE', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw/took dead whale/cut in/commenced boiling','barrels',NULL,'result','successful (dead whale)'), 'Finished boiling. Saw a dead whale, took him to the ship. Fine breezes from NE.', 0, 0),
    (@voyage_id, '1843-11-23 00:00:00', 'Pacific Ocean (whaling ground)', -36.667, -157.767, 'took whale; cut in; boiling', 'light breezes; fresh breezes later', 'N, then NNW', 'NNW', JSON_ARRAY(), JSON_OBJECT('type','whale (species not stated)','action','saw/lowered/struck/turned up/took alongside/cut in','barrels',NULL,'result','successful'), 'Took whale and cut him in. Employed boiling.', 0, 0),
    (@voyage_id, '1843-12-05 00:00:00', 'Pacific Ocean (en route to Cape Horn)', -39.833, -140.083, 'routine sailing', 'light breezes', 'W', 'ESE', JSON_ARRAY(), JSON_OBJECT(), '1 man sick.', 0, 0),
    (@voyage_id, '1843-12-08 00:00:00', 'Pacific Ocean (en route)', -42.500, -128.867, 'routine sailing', 'strong breezes', 'W', 'E', JSON_ARRAY(), JSON_OBJECT(), 'Longitude appears to be a log error; assumed to be more westward than 88.52W.', 0, 0),
    (@voyage_id, '1843-12-16 00:00:00', 'Pacific Ocean (en route)', -40.483, -105.783, 'sailing in heavy weather', 'light winds; strong breeze later; fresh breezes later', 'W, then N, then S', '', JSON_ARRAY(), JSON_OBJECT(), 'Took in topgalant sails and double reeft the topsails.', 0, 0),
    (@voyage_id, '1843-12-25 00:00:00', 'Atlantic Ocean (Cape Horn approach)', -52.017, -72.250, 'spoke barque; Christmas Day', 'fresh breezes; light breezes later', 'NNW, then NW', 'SE by E', JSON_ARRAY(JSON_OBJECT('name','North America (Barque)','home_port','New London')), JSON_OBJECT(), 'Spoke Barque North America. Longitude corrected for plausible route.', 0, 0),
    (@voyage_id, '1843-12-26 00:00:00', 'Atlantic Ocean (whaling attempt)', -52.750, -78.067, 'whaling attempt; sailing in heavy weather', 'light breezes; fresh gales later', 'W, then SW', 'E by S, then ESE', JSON_ARRAY(), JSON_OBJECT('type','sperm whale','action','lowered for two large','result','no success/came on board'), 'Lowered for two large Sperm Whale. Took in sail for the night.', 0, 0),
    (@voyage_id, '1843-12-30 00:00:00', 'Diego Ramirez Islands (made land)', -56.800, -69.100, 'made land; routine sailing', 'fine breezes; fresh breezes later', 'S', 'E, then E by N', JSON_ARRAY(), JSON_OBJECT(), 'Made the Islands of Diego Ramires (South of Cape Horn).', 0, 0),
    (@voyage_id, '1843-12-31 00:00:00', 'Off Cape Horn/Hermite Islands', -56.917, -67.683, 'made land (Cape Horn); heavy current; headwind', 'light breezes; calm later', 'S, then E', 'ESE, then N by W, then S', JSON_ARRAY(JSON_OBJECT('name','two Sail','home_port',NULL)), JSON_OBJECT(), 'Strong current setting down on the land. Saw the land of Cape Horn (Hermits Island). Tacked ship. Ends this year off Cape Horn with a head wind.', 0, 0),
    (@voyage_id, '1844-01-01 00:00:00', 'Off Cape Horn (departing)', -56.867, -66.583, 'spoke ship; made sail', 'fresh breezes; calm later; breeze later', 'SE, then N', 'NE, then ENE', JSON_ARRAY(JSON_OBJECT('name','Helena','home_port','Sagharbor')), JSON_OBJECT(), 'Spoke Ship Helena (72 days from home, clean).', 0, 0),
    (@voyage_id, '1844-01-03 00:00:00', 'Near Staten Land (Staten Island)', -55.367, -63.783, 'made Staten Land; spoke ship', 'fresh breezes; light breezes later', 'SSW, then WNW, then NE', 'N by W, then ESE, then N by W', JSON_ARRAY(JSON_OBJECT('name','English Ship','home_port','England')), JSON_OBJECT(), 'Saw English Ship bound round the Cape. Made the Island of Staten Land.', 0, 0),
    (@voyage_id, '1844-01-05 00:00:00', 'Atlantic Ocean (en route)', -51.783, -63.250, 'sailing in heavy weather; snow storms', 'fresh gales; blowing a gale later; fresh gales later', 'SW, then W', 'NNW', JSON_ARRAY(), JSON_OBJECT(), 'Blowing a gale. Heavy snow storms.', 0, 0),
    (@voyage_id, '1844-01-11 00:00:00', 'Atlantic Ocean (en route)', -42.217, -48.333, 'spoke ship; sailing in heavy weather', 'light breezes; fresh gales later', 'SW, then N', 'ENE', JSON_ARRAY(JSON_OBJECT('name','William C. Ney','home_port','New London')), JSON_OBJECT(), 'Spoke William C. Ney (72 days from home, clean). Double reeft topsails and foresail.', 0, 0),
    (@voyage_id, '1844-01-21 00:00:00', 'Atlantic Ocean (en route)', -34.000, -42.500, 'heavy weather; sail/rigging work', 'fresh breezes; hard squalls later; hard gales later', 'N, then N', '', JSON_ARRAY(), JSON_OBJECT(), 'Employed turning in the main topmast rigging. Heavy thunder storm. Blowing a gale with rain. Log keeper expects to be home in nine weeks ("if all is well").', 0, 0),
    (@voyage_id, '1844-01-27 00:00:00', 'Atlantic Ocean (en route)', -26.050, -41.750, 'sails/rigging work', 'fresh breezes; fresh breezes later', 'ENE, then NE', 'WNW, then NE', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Bent the new main topsail, sent the old one down for repairs. Employed refitting the main rigging. One sail in sight.', 0, 0),
    (@voyage_id, '1844-01-29 00:00:00', 'Atlantic Ocean (en route)', -25.717, -39.767, 'spoke ship; repairing sails', 'fresh gales', 'NNE', 'E', JSON_ARRAY(JSON_OBJECT('name','Dutch Gat yacht','home_port','Netherlands')), JSON_OBJECT(), 'Spoke a Dutch [Gat] Yacht standing to the south. Double reeft topsails. Employed repairing sails.', 0, 0),
    (@voyage_id, '1844-02-05 00:00:00', 'Atlantic Ocean (whaling ground)', -23.333, -37.083, 'took two sperm whales; boat stove; cutting in', 'fresh breezes; strong breezes later', 'NNE', 'E', JSON_ARRAY(), JSON_OBJECT('type','sperm whales','action','saw/lowered/struck 3/starboard boat got stove/cut 2/took alongside/commenced cutting','barrels',NULL,'result','successful (2 whales saved); 1 boat stove'), 'Lowered and struck 3. Starboard boat got stove. Saved two whale. Commenced cutting them.', 0, 0),
    (@voyage_id, '1844-02-07 00:00:00', 'Atlantic Ocean (whaling ground)', -23.233, -34.983, 'finished boiling; heading north', 'fine breezes', 'NNE, then NE', 'E, then NNW', JSON_ARRAY(), JSON_OBJECT(), 'Finished boiling. Tacked ship heading NNW.', 0, 0),
    (@voyage_id, '1844-02-22 00:00:00', 'Pernambuco (Brazil) approach', -8.000, -34.700, 'made land; preparing to anchor', 'fine breezes; fresh breezes later', 'SE', 'NNW', JSON_ARRAY(JSON_OBJECT('name','several sail','home_port',NULL), JSON_OBJECT('name','small boats','home_port',NULL)), JSON_OBJECT(), 'Made the land for the Port of Pernambuco on the coast of Brazil. Bent the cables and got all ready for coming to anchor. Longitude estimated.', 0, 0),
    (@voyage_id, '1844-02-23 00:00:00', 'Pernambuco Harbour (Brazil)', -8.050, -34.717, 'anchored; captain ashore; water party on shore', 'fine breezes', 'SE', 'NW in for the town', JSON_ARRAY(JSON_OBJECT('name','several ships','home_port',NULL)), JSON_OBJECT(), 'Brought the ship to anchor in 8 Fathoms water. Captain went on shore with two boats. Took 9 pipes on shore for the water.', 0, 0),
    (@voyage_id, '1844-02-24 00:00:00', 'Pernambuco Harbour (Departed)', -7.800, -34.600, 'provisioning; spoke barque; departed', 'fine weather; squally later; fine breezes later', 'SE', 'E, then ENE', JSON_ARRAY(JSON_OBJECT('name','North America (Barque)','home_port',NULL)), JSON_OBJECT(), 'Barque North America came to anchor. Took in the water. Got the ship under way.', 0, 0),
    (@voyage_id, '1844-02-28 00:00:00', 'Atlantic Ocean (en route home)', -0.667, -37.833, 'spoke ship; routine sailing; employed painting', 'fine breezes', 'NE', 'NW by N', JSON_ARRAY(JSON_OBJECT('name','Helvetia','home_port','New London')), JSON_OBJECT(), 'Spoke Ship Helvetia of New London, bound home. 40 miles south (of equator). Crew employed painting.', 0, 0),
    (@voyage_id, '1844-02-29 00:00:00', 'Atlantic Ocean (en route home)', -0.933, -39.667, 'in company with ship; parted company', 'fine breezes; squally with rain later; fresh breezes later', 'NE', 'NW by N', JSON_ARRAY(JSON_OBJECT('name','Helvetia','home_port','New London')), JSON_OBJECT(), 'In company with Ship Helvetia. Parted company at 7 PM.', 0, 0),
    (@voyage_id, '1844-03-01 00:00:00', 'Atlantic Ocean (en route home)', 2.933, -44.117, 'routine sailing', 'fresh breezes', 'NE', 'NW', JSON_ARRAY(), JSON_OBJECT(), 'Latitude is now North.', 0, 0);

-- ───────────────────────────────────────────────────────────────
-- Seed: Events (Indian Chief, March 1844 - April 1844)
-- Final leg of the voyage from Pernambuco to New London
-- ───────────────────────────────────────────────────────────────
INSERT INTO events
(voyage_id, date, location, latitude, longitude, activity, weather, wind_direction, course_direction, ships_encountered, whale_activity, notes, motivation_levels, casualties)
VALUES
    (@voyage_id, '1844-03-03 00:00:00', 'Atlantic Ocean (en route home)', 7.800, -46.583, 'routine sailing', 'fresh breezes', 'NE', 'NW by N', JSON_ARRAY(), JSON_OBJECT(), '', 0, 0),
    (@voyage_id, '1844-03-04 00:00:00', 'Atlantic Ocean (en route home)', 9.967, -48.200, 'whitewashing masts; saw blackfish', 'fresh breezes', 'NE', 'NW by N', JSON_ARRAY(), JSON_OBJECT('type','blackfish','action','saw','result',NULL), 'Employed whitewashing the lower masts and mast heads.', 0, 0),
    (@voyage_id, '1844-03-08 00:00:00', 'Atlantic Ocean (en route home)', 18.167, -56.100, 'routine sailing; saw ship', 'fine breezes', 'NE', 'NW by N', JSON_ARRAY(JSON_OBJECT('name','English ship','home_port','England')), JSON_OBJECT(), 'Saw an English ship standing to the SSW.', 0, 0),
    (@voyage_id, '1844-03-12 00:00:00', 'Atlantic Ocean (heavy squalls)', 24.467, -61.283, 'sailing in heavy weather', 'light winds/variable; fresh breezes; blowing a gale later', 'NW, then SE, then NW', '', JSON_ARRAY(), JSON_OBJECT(), 'Blowing a gale from NW, brought the ship under double reeft topsails.', 0, 0),
    (@voyage_id, '1844-03-17 00:00:00', 'Atlantic Ocean (whaling ground)', 27.250, -62.883, 'took sperm whale; commenced cutting', 'fine breezes; light breezes later', 'NE, then E', 'NW', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT('type','sperm whale','action','saw/lowered/struck/turned up/took alongside/commenced cutting','barrels',NULL,'result','successful'), 'Saw sperm whale at 6 AM. Took him alongside at 11 AM. Several whale in sight. One sail in sight. Note: Log summary mentions this as SSW of Bermuda. ', 0, 0),
    (@voyage_id, '1844-03-21 00:00:00', 'Atlantic Ocean (stowing)', 30.000, -67.000, 'stowing; boiling; sailing', 'fresh breezes; calm later; fine breezes later', 'NE, then SE, then W', 'NW by N', JSON_ARRAY(), JSON_OBJECT(), 'Employed stowing. Wind shifted to WSW, made all sail.', 0, 0),
    (@voyage_id, '1844-03-22 00:00:00', 'Atlantic Ocean (heavy weather/damage)', 31.300, -67.267, 'spoke schooner; lost gear; heavy weather', 'fresh breezes; fresh gales later; hard gales later', 'SW, then NW', 'NW by N', JSON_ARRAY(JSON_OBJECT('name','Marble Head (Schooner)','home_port','Marble Head')), JSON_OBJECT(), 'Spoke Schooner Marble Head (got papers and potatoes). Blowing a hard gale from NW with heavy rain squalls. Lost the lower studding sail boom.', 0, 0),
    (@voyage_id, '1844-03-24 00:00:00', 'Atlantic Ocean (gale/damage/oil leak)', 33.517, -68.217, 'sailing in severe gale; damage; oil leak', 'hard gales; heavy thunder squall', 'SW, then W', 'NNW', JSON_ARRAY(), JSON_OBJECT(), 'Heavy thunder squall split the foresail and main topsail. Oil got adrift between decks and started to leak. Laying too under close reeft main topsail.', 0, 0),
    (@voyage_id, '1844-03-28 00:00:00', 'Atlantic Ocean (near US Coast)', 37.633, -70.667, 'made sail; decommissioned gear', 'fresh breezes; squally; fresh breezes later', 'WSW, then SSW', 'NW', JSON_ARRAY(JSON_OBJECT('name','unknown','home_port',NULL)), JSON_OBJECT(), 'Sent down the cutting pendants and throwed the tryworks over board. A sail in sight.', 0, 0),
    (@voyage_id, '1844-03-30 00:00:00', 'Off New London Coast (sounding)', 40.483, -72.167, 'sailing; sounding/found bottom; spoke schooner', 'light breezes; fresh breezes later; blowing a gale later', 'NW, then NE', 'N by W, then SE', JSON_ARRAY(JSON_OBJECT('name','Roneoak (Schooner)','home_port','Greenport')), JSON_OBJECT(), 'Brought the ship too, sounded no bottom at 90 Fathoms. Later got soundings 45 Fathoms (specked sand). Spoke Schooner Roneoak.', 0, 0),
    (@voyage_id, '1844-03-31 00:00:00', 'Off New London Coast (cold gale)', 40.483, -71.833, 'sailing in heavy gale; sail frozen', 'hard gales; sharp frost; keen cold weather', 'NW, then NE', 'northern tack, then SE', JSON_ARRAY(), JSON_OBJECT(), 'Hard gales from NW. Had to thaw the sail (foresail) it being froze stiff. In 35 Fathoms water. Heading home.', 0, 0),
    (@voyage_id, '1844-04-04 00:00:00', 'Near Montauk Point (Long Island)', 41.000, -72.000, 'made land; prepared to stop', 'fine breezes; fresh breezes later; came on thick', 'WSW', 'N by E', JSON_ARRAY(), JSON_OBJECT(), 'Made Long Island at 10:30 AM. Saw Montauk Lighthouse at 11:30 AM. Brought the ship too with the main yard aback. Longitude estimated.', 0, 0),
    (@voyage_id, '1844-04-05 00:00:00', 'New London Harbour (Arrival)', 41.350, -72.098, 'took pilot; rounded point; anchored', 'fine breezes; clear weather later', 'SW', 'round Montauc Point', JSON_ARRAY(), JSON_OBJECT(), 'Took a pilot at 2 PM. Arrived in New London Harbour at 7:30 PM. So Ends this whaling voyage. ', 0, 0);

